export type MockupCatalogMap = Record<string, string | null>;

export const buildCatalogKey = (productionType: string, platform: string, format: string) =>
  `${productionType}::${platform}::${format}`;

export const mockupCatalogMap: MockupCatalogMap = {
  "midia-on::Instagram::Feed 1:1": "InstagramFeedMockup",
  "midia-on::Instagram::Feed 4:5": "InstagramFeedMockup",
  "midia-on::Instagram::Story 9:16": "InstagramStoryMockup",
  "midia-on::Instagram::Reels 9:16": "InstagramReel",
  "midia-on::Instagram::Carousel Feed 1:1": "InstagramCarousel",
  "midia-on::Instagram::Carousel Feed 4:5": "InstagramCarousel",
  "midia-on::Instagram::IGTV Cover 1:1": "InstagramFeedMockup",
  "midia-on::Instagram::IGTV Video 9:16": "InstagramFeedMockup",
  "midia-on::Instagram::Profile Picture": "InstagramProfileMockup",
  "midia-on::Instagram::Story Highlight Cover": "InstagramStoryMockup",
  "midia-on::Instagram::Story Ad 9:16": "InstagramStoryMockup",
  "midia-on::Instagram::Feed Video 1:1": "InstagramFeedMockup",
  "midia-on::Instagram::Feed Video 4:5": "InstagramFeedMockup",
  "midia-on::Instagram::Reels Ad 9:16": "InstagramReel",
  "midia-on::Instagram::Explore Ad 1:1": "InstagramAd",
  "midia-on::Instagram::Shopping Post 1:1": "InstagramFeedMockup",
  "midia-on::Instagram::Shopping Story 9:16": "InstagramStoryMockup",
  "midia-on::Instagram::Collection Ad": "InstagramAd",
  "midia-on::Instagram::Branded Content Ad 1:1": "InstagramAd",
  "midia-on::Instagram::Lead Ad Form": "InstagramAd",
  "midia-on::Facebook::Feed Image 1:1": "FacebookPost",
  "midia-on::Facebook::Feed Image 4:5": "FacebookPost",
  "midia-on::Facebook::Feed Image 16:9": "FacebookPost",
  "midia-on::Facebook::Feed Video 1:1": "FacebookPost",
  "midia-on::Facebook::Feed Video 4:5": "FacebookPost",
  "midia-on::Facebook::Feed Video 16:9": "FacebookPost",
  "midia-on::Facebook::Story 9:16": "FacebookStory",
  "midia-on::Facebook::Carousel 1:1": "FacebookCarousel",
  "midia-on::Facebook::Carousel Video": "FacebookCarousel",
  "midia-on::Facebook::Collection Ad": "FacebookAd",
  "midia-on::Facebook::Instant Experience": "FacebookAd",
  "midia-on::Facebook::Lead Ad Form": "FacebookAd",
  "midia-on::Facebook::Messenger Ad": "FacebookAd",
  "midia-on::Facebook::Marketplace Ad": "FacebookMarketplace",
  "midia-on::Facebook::Right Column Desktop": "FacebookAd",
  "midia-on::Facebook::In-Stream Video Ad": "FacebookWatch",
  "midia-on::Facebook::Event Ad": "FacebookEvent",
  "midia-on::Facebook::Page Like Ad": "FacebookAd",
  "midia-on::Facebook::Offer Ad": "FacebookAd",
  "midia-on::Facebook::Dynamic Product Ad": "FacebookAd",
  "midia-on::Facebook::Slideshow Ad": "FacebookAd",
  "midia-on::Facebook::Playable Ad": "FacebookAd",
  "midia-on::Facebook::Augmented Reality Ad": "FacebookAd",
  "midia-on::Facebook::Poll Ad": "FacebookPoll",
  "midia-on::Facebook::Branded Content Ad": "FacebookAd",
  "midia-on::TikTok::In-Feed Ad 9:16": "TikTokVideo",
  "midia-on::TikTok::TopView Ad 9:16": "TikTokVideo",
  "midia-on::TikTok::Brand Takeover": "TikTokVideo",
  "midia-on::TikTok::Branded Hashtag Challenge": "TikTokVideo",
  "midia-on::TikTok::Branded Effect": "TikTokEffect",
  "midia-on::TikTok::Spark Ads": "TikTokVideo",
  "midia-on::TikTok::Collection Ad": "TikTokVideo",
  "midia-on::TikTok::Dynamic Showcase Ad": "TikTokVideo",
  "midia-on::TikTok::Lead Generation Ad": "TikTokVideo",
  "midia-on::TikTok::App Install Ad": "TikTokVideo",
  "midia-on::YouTube::Skippable In-Stream Ad 16:9": "YouTubeVideo",
  "midia-on::YouTube::Non-Skippable In-Stream Ad 16:9": "YouTubeVideo",
  "midia-on::YouTube::Bumper Ad 16:9": "YouTubeVideo",
  "midia-on::YouTube::Shorts Ad 9:16": "YouTubeShorts",
  "midia-on::YouTube::Discovery Ad": "YouTubeVideo",
  "midia-on::YouTube::Masthead Desktop": "YouTubeBanner",
  "midia-on::YouTube::Masthead Mobile": "YouTubeBanner",
  "midia-on::YouTube::Overlay Ad": "YouTubeVideo",
  "midia-on::YouTube::Display Ad Desktop": "YouTubeVideo",
  "midia-on::YouTube::Sponsored Card": "YouTubeVideo",
  "midia-on::YouTube::Outstream Ad Mobile": "YouTubeVideo",
  "midia-on::YouTube::App Install Ad": "YouTubeVideo",
  "midia-on::YouTube::Shopping Ad": "YouTubeVideo",
  "midia-on::YouTube::Lead Form Ad": "YouTubeVideo",
  "midia-on::YouTube::Action Campaign": "YouTubeVideo",
  "midia-on::LinkedIn::Single Image Ad 1:1": "LinkedInAd",
  "midia-on::LinkedIn::Single Image Ad 16:9": "LinkedInAd",
  "midia-on::LinkedIn::Video Ad 16:9": "LinkedInAd",
  "midia-on::LinkedIn::Video Ad 1:1": "LinkedInAd",
  "midia-on::LinkedIn::Video Ad 9:16": "LinkedInAd",
  "midia-on::LinkedIn::Carousel Ad": "LinkedInAd",
  "midia-on::LinkedIn::Document Ad": "LinkedInArticle",
  "midia-on::LinkedIn::Event Ad": "LinkedInEvent",
  "midia-on::LinkedIn::Lead Gen Form Ad": "LinkedInAd",
  "midia-on::LinkedIn::Message Ad": "LinkedInAd",
  "midia-on::LinkedIn::Conversation Ad": "LinkedInAd",
  "midia-on::LinkedIn::Text Ad": "LinkedInAd",
  "midia-on::LinkedIn::Spotlight Ad": "LinkedInAd",
  "midia-on::LinkedIn::Follower Ad": "LinkedInAd",
  "midia-on::LinkedIn::Job Ad": "LinkedInJobPost",
  "midia-on::Google Display::Medium Rectangle 300x250": "GoogleBanner300x250",
  "midia-on::Google Display::Large Rectangle 336x280": "GoogleDisplayAd",
  "midia-on::Google Display::Leaderboard 728x90": "GoogleBanner728x90",
  "midia-on::Google Display::Large Leaderboard 970x90": "GoogleDisplayAd",
  "midia-on::Google Display::Billboard 970x250": "GoogleBanner970x250",
  "midia-on::Google Display::Half Page 300x600": "GoogleBanner300x600",
  "midia-on::Google Display::Wide Skyscraper 160x600": "GoogleBanner160x600",
  "midia-on::Google Display::Skyscraper 120x600": "GoogleDisplayAd",
  "midia-on::Google Display::Mobile Banner 320x50": "GoogleDisplayAd",
  "midia-on::Google Display::Large Mobile Banner 320x100": "GoogleDisplayAd",
  "midia-on::Google Display::Small Square 200x200": "GoogleDisplayAd",
  "midia-on::Google Display::Square 250x250": "GoogleDisplayAd",
  "midia-on::Google Display::Small Rectangle 180x150": "GoogleDisplayAd",
  "midia-on::Google Display::Vertical Rectangle 240x400": "GoogleDisplayAd",
  "midia-on::Google Display::Triple Widescreen 250x360": "GoogleDisplayAd",
  "midia-on::Google Display::Responsive Display Ad": "GoogleResponsiveAd",
  "midia-on::Google Display::Gmail Ad": "GoogleDisplayAd",
  "midia-on::Google Display::HTML5 Banner Responsive": "GoogleResponsiveAd",
  "midia-on::Google Display::Lightbox Ad": "GoogleDisplayAd",
  "midia-on::Google Display::App Install Ad": "GoogleDisplayAd",
  "midia-on::Twitter/X::Image Ad 1:1": "TwitterAd",
  "midia-on::Twitter/X::Image Ad 16:9": "TwitterAd",
  "midia-on::Twitter/X::Video Ad 16:9": "TwitterAd",
  "midia-on::Twitter/X::Video Ad 1:1": "TwitterAd",
  "midia-on::Twitter/X::Carousel Ad": "TwitterAd",
  "midia-on::Twitter/X::Moment Ad": "TwitterMoment",
  "midia-on::Twitter/X::Poll Ad": "TwitterPoll",
  "midia-on::Twitter/X::Amplify Pre-Roll": "TwitterPost",
  "midia-on::Twitter/X::Takeover Ad": "TwitterAd",
  "midia-on::Twitter/X::App Install Ad": "TwitterAd",
  "midia-on::Pinterest::Standard Pin 2:3": "PinterestPin",
  "midia-on::Pinterest::Square Pin 1:1": "PinterestPin",
  "midia-on::Pinterest::Long Pin 1:2.1": "PinterestPin",
  "midia-on::Pinterest::Video Pin 1:1": "PinterestPin",
  "midia-on::Pinterest::Video Pin 2:3": "PinterestPin",
  "midia-on::Pinterest::Carousel Pin": "PinterestPin",
  "midia-on::Pinterest::Shopping Pin": "PinterestShop",
  "midia-on::Pinterest::Collections Pin": "PinterestShop",
  "midia-on::Pinterest::Idea Pin": "PinterestIdeaPin",
  "midia-on::Pinterest::Try On Pin": "PinterestPin",
  "midia-on::Snapchat::Single Image or Video Ad 9:16": "SnapchatSnap",
  "midia-on::Snapchat::Story Ad": "SnapchatStory",
  "midia-on::Snapchat::Collection Ad": "SnapchatSnap",
  "midia-on::Snapchat::AR Lens": "SnapchatSnap",
  "midia-on::Snapchat::Filters": "SnapchatSnap",
  "midia-on::Snapchat::Commercial": "SnapchatSnap",
  "midia-on::Snapchat::Dynamic Ad": "SnapchatSnap",
  "midia-on::Snapchat::App Install Ad": "SnapchatSnap",
  "midia-on::Snapchat::Lead Generation Ad": "SnapchatSnap",
  "midia-on::Snapchat::Long-Form Video Ad": "SnapchatSnap",
  "midia-on::Meta Audience Network::Native Banner": "FacebookAd",
  "midia-on::Meta Audience Network::Interstitial": "FacebookAd",
  "midia-on::Meta Audience Network::Rewarded Video": "FacebookAd",
  "midia-on::Meta Audience Network::In-Stream Video": "FacebookAd",
  "midia-on::Meta Audience Network::Playable Ad": "FacebookAd",
  "midia-off::OOH::Outdoor 9x3m": "Outdoor9x3",
  "midia-off::OOH::Frontlight 9x3m": "Outdoor9x3",
  "midia-off::OOH::Backlight 9x3m": "Outdoor9x3",
  "midia-off::OOH::Busdoor 2x1m": "OutdoorBusdoor",
  "midia-off::OOH::Painel de LED Digital": "OutdoorDigital",
  "midia-off::OOH::Relógio de Rua": "OutdoorRelogio",
  "midia-off::OOH::Abrigo de Ônibus": "AbrigoOnibus",
  "midia-off::OOH::Empena de Prédio": "OutdoorEmpena",
  "midia-off::OOH::Topo de Táxi": "OutdoorTaxi",
  "midia-off::OOH::Metrô - Painel de Plataforma": "MetroPlataforma",
  "midia-off::OOH::Aeroporto - Painel": "AeroportoPainel",
  "midia-off::OOH::Shopping - Painel": "OutdoorTotem",
  "midia-off::OOH::Elevador - Painel Interno": "OutdoorTotem",
  "midia-off::OOH::Estádio - Painel de Campo": "OutdoorDigital",
  "midia-off::OOH::Banheiro - Painel": "OutdoorTotem",
  "midia-off::TV::Comercial 15s": "TVCommercial15s",
  "midia-off::TV::Comercial 30s": "TVCommercial30s",
  "midia-off::TV::Comercial 60s": "TVCommercial60s",
  "midia-off::TV::Vinheta 5s": "TVVinheta",
  "midia-off::TV::Infomercial 2min": "TVTeleshopping",
  "midia-off::TV::Patrocínio de Programa": "TVPatrocinio",
  "midia-off::TV::Product Placement": "TVProductPlacement",
  "midia-off::TV::Testemunhal": "TVTestemunhal",
  "midia-off::TV::Animação/Motion Graphics": "TVAnimacao",
  "midia-off::TV::Split Screen": "TVComparativo",
  "midia-off::Rádio::Spot 15s": "RadioSpot15s",
  "midia-off::Rádio::Spot 30s": "RadioSpot30s",
  "midia-off::Rádio::Spot 60s": "RadioSpot60s",
  "midia-off::Rádio::Jingle": "RadioJingle",
  "midia-off::Rádio::Testemunhal ao Vivo": "RadioTestemunhal",
  "midia-off::Revista::Página Inteira": "RevistaPaginaSimples",
  "midia-off::Revista::Meia Página": "RevistaMeiaPagina",
  "midia-off::Revista::Página Dupla": "RevistaPaginaDupla",
  "midia-off::Jornal::Página Inteira": "JornalPaginaInteira",
  "midia-off::Jornal::Meia Página": "JornalMeiaPagina",
  "midia-off::Jornal::Coluna (1/4 de página)": "JornalColuna",
  "midia-off::Flyer::A5 (14.8x21cm)": "RevistaPaginaSimples",
  "midia-off::Folder::A4 Dobrado (21x29.7cm)": "RevistaPaginaSimples",
  "midia-off::Catálogo::A4 (21x29.7cm)": "RevistaBooklet",
  "midia-off::Encarte::Customizado": "JornalEncarte",
  "eventos-ativacoes::Evento::Banner Roll-up 85x200cm": "EstandeBanner",
  "eventos-ativacoes::Evento::Banner Roll-up 100x200cm": "EstandeBanner",
  "eventos-ativacoes::Evento::Backdrop 3x2m": "BackdropPalco",
  "eventos-ativacoes::Evento::Backdrop 4x3m": "BackdropPalco",
  "eventos-ativacoes::Evento::Totem Inflável": "TotemExterno",
  "eventos-ativacoes::Evento::Totem de Chão": "TotemExterno",
  "eventos-ativacoes::Evento::Credencial 9x5cm": "Agenda",
  "eventos-ativacoes::Evento::Crachá 10x7cm": "Agenda",
  "eventos-ativacoes::Evento::Faixa 5x1m": "FaixaFachada",
  "eventos-ativacoes::Evento::Lona 3x2m": "FaixaFachada",
  "eventos-ativacoes::Evento::Display de Balcão": "DisplayBalcao",
  "eventos-ativacoes::Evento::Bandeira Personalizada": "BandeiraVento",
  "eventos-ativacoes::Brinde::Camiseta": "Camiseta",
  "eventos-ativacoes::Brinde::Caneca": "Copo",
  "eventos-ativacoes::Brinde::Ecobag": "Ecobag",
  "eventos-ativacoes::Brinde::Boné": "Bone",
  "eventos-ativacoes::Brinde::Caderno/Bloco de Notas": "Caderno",
  "eventos-ativacoes::Brinde::Caneta": "Caneta",
  "eventos-ativacoes::Brinde::Pen Drive": "PenDrive",
  "eventos-ativacoes::Brinde::Adesivo": "AdesivoVidro",
  "eventos-ativacoes::Sinalização::Placa de Direção": "PlacaDirecional",
  "eventos-ativacoes::Sinalização::Placa de Identificação": "PlacaDirecional",
  "eventos-ativacoes::Sinalização::Adesivo de Chão": "AdesivoVidro",
  "eventos-ativacoes::Cenografia::Painel de Palco": "PalcoEvento",
  "eventos-ativacoes::Cenografia::Cortina de LED": "PainelLED",
  "eventos-ativacoes::Ativação::Tenda Personalizada 3x3m": "EstandeGrande",
  "eventos-ativacoes::Ativação::Balcão Promocional": "AreaPromocional",
  "eventos-ativacoes::Ativação::Photobooth Frame": "PhotoBooth",
  "eventos-ativacoes::Ativação::Painel Interativo": "AreaPromocional",
  "eventos-ativacoes::Ativação::Jogo/Gamificação": "AreaPromocional",
  "endomarketing::Digital::Newsletter HTML": "NewsletterCampanha",
  "endomarketing::Digital::Email Signature": "AssinaturaEmail",
  "endomarketing::Digital::TV Corporativa 16:9": "TVCorporativaAvisos",
  "endomarketing::Digital::Wallpaper Desktop 1920x1080": "TVCorporativaClima",
  "endomarketing::Digital::Screensaver": "TVCorporativaClima",
  "endomarketing::Digital::Intranet Banner 1200x400": "NewsletterCampanha",
  "endomarketing::Digital::Intranet Card 400x300": "NewsletterCampanha",
  "endomarketing::Digital::Teams/Slack Banner": "NewsletterCampanha",
  "endomarketing::Impresso::Cartaz A3 (29.7x42cm)": "ManualColaborador",
  "endomarketing::Impresso::Cartaz A4 (21x29.7cm)": "ManualColaborador",
  "endomarketing::Impresso::Mural de Avisos": "ManualColaborador",
  "endomarketing::Impresso::Comunicado A4": "ManualColaborador",
  "endomarketing::Impresso::Manual do Colaborador": "ManualColaborador",
  "endomarketing::Impresso::Guia de Onboarding": "ManualIntegracao",
  "endomarketing::Impresso::Revista Interna": "NewsletterMensal",
  "endomarketing::Impresso::Calendário de Parede": "ManualProcedimentos",
  "endomarketing::Impresso::Planner/Agenda": "ManualProcedimentos",
  "endomarketing::Impresso::Adesivo Motivacional": "ManualSeguranca",
  "endomarketing::Impresso::Placa de Porta": "ManualSeguranca",
  "endomarketing::Impresso::Placa de Sinalização Interna": "ManualSeguranca",
  "endomarketing::Impresso::Certificado de Reconhecimento": "Certificado",
  "endomarketing::Digital::GIF Animado para Email": "NewsletterCampanha",
  "endomarketing::Digital::Infográfico Vertical": "NewsletterCampanha",
  "endomarketing::Digital::Vídeo de Treinamento 16:9": "YouTubeVideo",
  "endomarketing::Digital::Podcast Cover Art": "SpotifyPodcast",
  "apresentacoes::PowerPoint/Keynote::Pitch Deck 16:9": "KeynoteCapa",
  "apresentacoes::PowerPoint/Keynote::Apresentação Corporativa 16:9": "KeynoteConteudo",
  "apresentacoes::PowerPoint/Keynote::Apresentação de Vendas 16:9": "KeynoteConteudo",
  "apresentacoes::PowerPoint/Keynote::Relatório Executivo 16:9": "KeynoteDados",
  "apresentacoes::PowerPoint/Keynote::Apresentação de Treinamento 16:9": "KeynoteConteudo",
  "apresentacoes::PowerPoint/Keynote::Apresentação de Resultados 16:9": "KeynoteConteudo",
  "apresentacoes::PowerPoint/Keynote::Apresentação 4:3 (Legacy)": "KeynoteConteudo",
  "apresentacoes::PowerPoint/Keynote::Slide Vertical 9:16": "KeynoteConteudo",
  "apresentacoes::Google Slides::Apresentação Online 16:9": "KeynoteConteudo",
  "apresentacoes::Prezi::Apresentação Não-Linear": "KeynoteConteudo",
  "apresentacoes::Canva::Apresentação Simplificada 16:9": "KeynoteConteudo",
  "apresentacoes::PDF::Documento de Apresentação A4": "KeynoteConteudo",
  "apresentacoes::Infográfico::One-Pager Vertical": "KeynoteResumo",
  "apresentacoes::Video::Apresentação em Vídeo 16:9": "KeynoteConteudo",
  "apresentacoes::Interactive::Apresentação Interativa HTML5": "KeynoteConteudo",
  "branding::Logo::Logo Principal Horizontal": "LogoPrincipal",
  "branding::Logo::Logo Principal Vertical": "LogoPrincipal",
  "branding::Logo::Logo Símbolo/Ícone": "LogoIcone",
  "branding::Logo::Logo Monocromático": "LogoMonocromatico",
  "branding::Logo::Logo Negativo (Fundo Escuro)": "LogoNegativo",
  "branding::Papelaria::Cartão de Visita 9x5cm": "CartaoVisita",
  "branding::Papelaria::Papel Timbrado A4": "Papelaria",
  "branding::Papelaria::Envelope Comercial": "Envelope",
  "branding::Papelaria::Pasta Corporativa": "BrandbookCapa",
  "branding::Papelaria::Bloco de Notas": "BrandbookCapa",
  "branding::Digital::Favicon 32x32": "LogoFavicon",
  "branding::Digital::App Icon iOS 1024x1024": "LogoIcone",
  "branding::Digital::App Icon Android 512x512": "LogoIcone",
  "branding::Digital::Social Media Profile Picture 400x400": "CapaRedes",
  "branding::Digital::Email Header": "AssinaturaEmail",
  "branding::Manual::Brand Guidelines": "BrandbookDiretrizes",
  "branding::Manual::Style Guide": "BrandbookDiretrizes",
  "branding::Sinalização::Fachada": "PlacaFachada",
  "branding::Sinalização::Letreiro Luminoso": "LetreiroCaixa",
  "branding::Sinalização::Placa de Identificação Externa": "PlacaFachada",
  "branding::Uniforme::Camiseta Corporativa": "Uniforme",
  "branding::Uniforme::Polo Corporativa": "Uniforme",
  "branding::Uniforme::Avental": "Uniforme",
  "branding::Veículo::Adesivação de Veículo": "BrandbookCapa",
  "branding::Embalagem::Caixa de Produto": "DisplayProduto",
  "branding::Embalagem::Sacola Personalizada": "DisplayProduto",
  "branding::Embalagem::Etiqueta de Produto": "DisplayProduto",
  "branding::Merchandising::Display de Ponto de Venda": "DisplayProduto",
  "branding::Merchandising::Wobbler": "DisplayProduto",
  "branding::Merchandising::Stopper de Gôndola": "DisplayProduto",
  "midia-on::WhatsApp Business::Status Image": "WhatsAppStatus",
  "midia-on::WhatsApp Business::Status Video": "WhatsAppStatus",
  "midia-on::WhatsApp Business::Product Catalog Image": "WhatsAppBusiness",
  "midia-on::WhatsApp Business::Message Template": "WhatsAppMessage",
  "midia-on::WhatsApp Business::Click-to-WhatsApp Ad": "WhatsAppMessage",
  "midia-on::Telegram Ads::Channel Post Sponsored": "TelegramChannel",
  "midia-on::Telegram Ads::Story Ad": "TelegramMessage",
  "midia-on::Telegram Ads::Bot Message": "TelegramMessage",
  "midia-on::Telegram Ads::Inline Button Ad": "TelegramMessage",
  "midia-on::Telegram Ads::Sticker Pack Sponsored": "TelegramMessage",
  "midia-on::Reddit Ads::Feed Image Ad": "RedditPost",
  "midia-on::Reddit Ads::Feed Video Ad": "RedditPost",
  "midia-on::Reddit Ads::Carousel Ad": "RedditPost",
  "midia-on::Reddit Ads::Conversation Ad": "RedditPost",
  "midia-on::Reddit Ads::Takeover Ad": "RedditPost",
  "midia-on::Reddit Ads::AMA (Ask Me Anything) Sponsored": "RedditPost",
  "midia-on::Twitch::Pre-roll Video Ad": "YouTubeVideo",
  "midia-on::Twitch::Mid-roll Video Ad": "YouTubeVideo",
  "midia-on::Twitch::Display Ad": "YouTubeVideo",
  "midia-on::Twitch::Homepage Takeover": "YouTubeVideo",
  "midia-on::Twitch::Sponsored Stream Overlay": "YouTubeVideo",
  "midia-on::Twitch::Bits Sponsorship": "YouTubeVideo",
  "midia-on::Spotify Ads::Audio Ad": "SpotifyPodcast",
  "midia-on::Spotify Ads::Video Takeover": "SpotifyPodcast",
  "midia-on::Spotify Ads::Homepage Takeover": "SpotifyPodcast",
  "midia-on::Spotify Ads::Podcast Ad": "SpotifyPodcast",
  "midia-on::Spotify Ads::Sponsored Playlist Cover": "SpotifyPlaylist",
  "midia-on::Spotify Ads::Overlay Ad": "SpotifyPodcast",
  "midia-on::Amazon Ads::Sponsored Products": "GoogleShoppingAd",
  "midia-on::Amazon Ads::Sponsored Brands Banner": "GoogleDisplayAd",
  "midia-on::Amazon Ads::Sponsored Brands Video": "GoogleVideoAd",
  "midia-on::Amazon Ads::Display Ad - Rectangle": "GoogleDisplayAd",
  "midia-on::Amazon Ads::Display Ad - Leaderboard": "GoogleDisplayAd",
  "midia-on::Amazon Ads::Fire TV Ad": "GoogleDisplayAd",
  "midia-on::Amazon Ads::Stores Page": "GoogleShoppingAd",
  "midia-on::Amazon Ads::Posts": "GoogleShoppingAd",
  "midia-on::Apple Search Ads::Search Results Ad": "GoogleSearchAd",
  "midia-on::Apple Search Ads::Today Tab Ad": "GoogleSearchAd",
  "midia-on::Apple Search Ads::Product Page Ad": "GoogleSearchAd",
  "midia-on::Microsoft Ads::Bing Search Text Ad": "GoogleSearchAd",
  "midia-on::Microsoft Ads::Bing Display Ad": "GoogleDisplayAd",
  "midia-on::Microsoft Ads::Bing Shopping Ad": "GoogleShoppingAd",
  "midia-on::Microsoft Ads::LinkedIn Sponsored Content (via Microsoft)": "LinkedInAd",
  "midia-on::Microsoft Ads::Audience Network Ad": "GoogleDisplayAd",
  "midia-on::Taboola/Outbrain::Native Feed Ad": "GoogleNativeAd",
  "midia-on::Taboola/Outbrain::Native Video Ad": "GoogleNativeAd",
  "midia-on::Taboola/Outbrain::Widget Ad": "GoogleNativeAd",
  "midia-on::Taboola/Outbrain::Sponsored Content": "GoogleNativeAd",
  "midia-on::Email Marketing::Newsletter Header": "NewsletterCampanha",
  "midia-on::Email Marketing::Email Banner": "NewsletterCampanha",
  "midia-on::Email Marketing::Email Signature": "NewsletterCampanha",
  "midia-on::Email Marketing::Promotional Email": "NewsletterCampanha",
  "midia-on::Email Marketing::Transactional Email": "NewsletterCampanha",
  "midia-on::Push Notifications::Web Push": "WhatsAppMessage",
  "midia-on::Push Notifications::Mobile Push": "WhatsAppMessage",
  "midia-on::Push Notifications::Rich Push": "WhatsAppMessage",
  "midia-on::In-App Ads::Interstitial Ad": "GoogleInterstitial",
  "midia-on::In-App Ads::Rewarded Video Ad": "GoogleVideoAd",
  "midia-on::In-App Ads::Native In-App Ad": "GoogleNativeAd",
  "midia-on::In-App Ads::Banner Ad": "GoogleDisplayAd",
  "midia-off::Cinema::Pre-show Ad 15s": "TVCinema",
  "midia-off::Cinema::Pre-show Ad 30s": "TVCinema",
  "midia-off::Cinema::Trailer Ad 60s": "TVCinema",
  "midia-off::Cinema::Lobby Display": "TVCinema",
  "midia-off::Cinema::Standee 3D": "TVCinema",
  "midia-off::Ponto de Venda::Expositor de Balcão": "DisplayBalcao",
  "midia-off::Ponto de Venda::Expositor de Chão": "DisplayChao",
  "midia-off::Ponto de Venda::Wobbler": "WobbleMobile",
  "midia-off::Ponto de Venda::Stopper": "StopperGondola",
  "midia-off::Ponto de Venda::Testeira": "FaixaFachada",
  "midia-off::Ponto de Venda::Faixa de Gôndola": "FaixaGondola",
  "midia-off::Ponto de Venda::Adesivo de Vitrine": "AdesivoVidro",
  "midia-off::Ponto de Venda::Display Digital PDV": "PainelLED",
  "midia-off::Ponto de Venda::Promotor Kit": "KitEscritorio",
  "midia-off::Ponto de Venda::Etiqueta de Preço Promocional": "DisplayProduto",
  "midia-off::Mídia Aérea::Banner Aéreo (Avião)": "OutdoorEmpena",
  "midia-off::Mídia Aérea::Balão Inflável": "OutdoorEmpena",
  "midia-off::Mídia Aérea::Drone Banner": "OutdoorEmpena",
  "midia-off::Mídia Aérea::Projeção Aérea": "OutdoorEmpena",
  "midia-off::Mídia em Movimento::Bike Banner": "OutdoorBusdoor",
  "midia-off::Mídia em Movimento::Moto Banner": "OutdoorBusdoor",
  "midia-off::Mídia em Movimento::Patinete Elétrico Ad": "OutdoorBusdoor",
  "midia-off::Mídia em Movimento::Carro de Som": "OutdoorBusdoor",
  "midia-off::Mídia em Movimento::Truck Banner": "OutdoorBusdoor",
  "midia-off::Projeção::Mapeamento 3D": "OutdoorDigital",
  "midia-off::Projeção::Projeção em Prédio": "OutdoorDigital",
  "midia-off::Holografia::Display Holográfico": "OutdoorDigital",
  "midia-off::Mídia Aquática::Barco Banner": "OutdoorDigital",
  "midia-off::Mídia Aquática::Jet Ski Banner": "OutdoorDigital",
  "eventos-ativacoes::Estruturas::Palco Backdrop": "BackdropPalco",
  "eventos-ativacoes::Estruturas::Camarote Branding": "EstruturaSuspensa",
  "eventos-ativacoes::Estruturas::Lounge Decoration": "EstruturaSuspensa",
  "eventos-ativacoes::Estruturas::Stand Completo": "EstruturaSuspensa",
  "eventos-ativacoes::Estruturas::Arco Inflável": "EstruturaSuspensa",
  "eventos-ativacoes::Tecnologia::Realidade Virtual Experience": "PainelLED",
  "eventos-ativacoes::Tecnologia::Realidade Aumentada Filter": "PainelLED",
  "eventos-ativacoes::Tecnologia::Holograma Display": "DisplayBalcao",
  "eventos-ativacoes::Tecnologia::LED Wall Content": "PainelLED",
  "eventos-ativacoes::Tecnologia::Interactive Touch Screen": "PainelLED",
  "eventos-ativacoes::Experiências::Photo Booth 360°": "PhotoBooth",
  "eventos-ativacoes::Experiências::Espelho Mágico": "AreaPromocional",
  "eventos-ativacoes::Experiências::Parede de LED Interativa": "PainelLED",
  "eventos-ativacoes::Experiências::Sampling Kit": "AreaPromocional",
  "eventos-ativacoes::Experiências::Pop-up Store Design": "AreaPromocional",
  "eventos-ativacoes::Materiais::Pulseira de Evento": "Caderno",
  "eventos-ativacoes::Materiais::Lanyard Personalizado": "Caderno",
  "eventos-ativacoes::Materiais::Sacola VIP": "Caderno",
  "eventos-ativacoes::Materiais::Press Kit": "Caderno",
  "eventos-ativacoes::Materiais::Convite Digital Interativo": "Caderno",
  "endomarketing::Vídeo::Onboarding Video": "ManualIntegracao",
  "endomarketing::Vídeo::CEO Message": "NewsletterCampanha",
  "endomarketing::Vídeo::Town Hall Recording": "YouTubeVideo",
  "endomarketing::Vídeo::Training Video": "YouTubeVideo",
  "endomarketing::Vídeo::Team Celebration Video": "YouTubeVideo",
  "endomarketing::Gamificação::Quiz Interativo": "SlideQuiz",
  "endomarketing::Gamificação::Ranking Board": "TVCorporativaKPIs",
  "endomarketing::Gamificação::Desafio Mensal": "NewsletterCampanha",
  "endomarketing::Gamificação::Badge Collection": "Badge",
  "endomarketing::Gamificação::Leaderboard Display": "TVCorporativaKPIs",
  "endomarketing::Reconhecimento::Troféu Personalizado": "NewsletterCampanha",
  "endomarketing::Reconhecimento::Placa de Reconhecimento": "ManualSeguranca",
  "endomarketing::Reconhecimento::Medalha Corporativa": "NewsletterCampanha",
  "endomarketing::Reconhecimento::Certificado Digital": "Certificado",
  "endomarketing::Reconhecimento::Employee of the Month": "NewsletterCampanha",
  "apresentacoes::Interativo::Webinar Slides": "KeynoteConteudo",
  "apresentacoes::Interativo::Demo Day Presentation": "KeynoteCapa",
  "apresentacoes::Interativo::Investor Deck": "KeynoteCapa",
  "apresentacoes::Interativo::Mentimeter Integration": "KeynoteComparacao",
  "apresentacoes::Interativo::Slido Q&A Slides": "KeynoteConteudo",
  "apresentacoes::Interativo::Kahoot Quiz Slides": "KeynoteConteudo",
  "apresentacoes::Vídeo::Loom Presentation": "KeynoteConteudo",
  "apresentacoes::Vídeo::Vidyard Sales Video": "KeynoteConteudo",
  "apresentacoes::Vídeo::Animated Explainer": "KeynoteConteudo",
  "apresentacoes::Interativo::Virtual Event Presentation": "KeynoteConteudo",
  "branding::Packaging::Caixa de Luxo": "DisplayProduto",
  "branding::Packaging::Embalagem Sustentável": "DisplayProduto",
  "branding::Packaging::Gift Box": "BrandbookCapa",
  "branding::Packaging::Rótulo de Produto": "DisplayProduto",
  "branding::Packaging::Sachet/Sachê": "DisplayProduto",
  "branding::Packaging::Sleeve/Luva": "DisplayProduto",
  "branding::Packaging::Blister Pack": "DisplayProduto",
  "branding::Packaging::Standup Pouch": "DisplayProduto",
  "branding::Digital Assets::Animated Logo": "LogoVariacoes",
  "branding::Digital Assets::Sound Logo": "LogoVariacoes",
  "branding::Digital Assets::Brand Video": "YouTubeVideo",
  "branding::Digital Assets::Social Media Kit": "BrandbookCapa",
  "branding::Digital Assets::Icon Set": "BrandbookIconografia",
  "branding::Digital Assets::Illustration Set": "BrandbookAplicacoes",
  "branding::Digital Assets::Pattern Library": "BrandbookPadrao",
  "branding::Digital Assets::Email Signature Template": "AssinaturaEmail",
  "branding::Digital Assets::Zoom Background": "CapaRedes",
  "branding::Digital Assets::Loading Animation": "YouTubeVideo",
  "branding::Motion Graphics::Brand Animation": "YouTubeVideo",
  "branding::Motion Graphics::Transitions Pack": "YouTubeVideo",
  "branding::Motion Graphics::Stingers": "YouTubeVideo",
  "branding::Motion Graphics::Lower Third": "YouTubeVideo",
  "branding::Motion Graphics::End Screen": "YouTubeVideo",
  "branding::3D Assets::Logo 3D": "LogoVariacoes",
  "branding::3D Assets::Product Render": "ProdutoDetalhes",
  "branding::3D Assets::Packaging Mockup 3D": "DisplayProduto",
  "branding::3D Assets::Environment Render": "ProdutoDetalhes",
  "branding::3D Assets::360° Product View": "ProdutoDetalhes",
  "branding::Brindes Premium::Garrafa Térmica Personalizada": "BrandbookCapa",
  "branding::Brindes Premium::Mochila Corporativa": "BrandbookCapa",
  "branding::Brindes Premium::Power Bank Personalizado": "BrandbookCapa",
  "branding::Brindes Premium::Caderno Moleskine": "BrandbookCapa",
  "branding::Brindes Premium::Caneta Premium": "BrandbookCapa",
  "branding::Brindes Premium::Kit Executivo": "BrandbookCapa",
  "branding::Brindes Premium::Relógio Corporativo": "BrandbookCapa",
  "e-commerce::Product Photography::Product Shot White Background": "ProdutoDetalhes",
  "e-commerce::Product Photography::Lifestyle Product Photo": "ProdutoDetalhes",
  "e-commerce::Product Photography::Product 360° View": "ProdutoDetalhes",
  "e-commerce::Product Photography::Product Detail Shot": "ProdutoDetalhes",
  "e-commerce::Product Photography::Product Size Comparison": "ComparacaoProdutos",
  "e-commerce::AR/VR::AR Try-On": "ProdutoDetalhes",
  "e-commerce::AR/VR::AR Product Placement": "ProdutoDetalhes",
  "e-commerce::Product Video::Product Demo Video": "ProdutoDetalhes",
  "e-commerce::Product Video::Unboxing Video": "YouTubeVideo",
  "e-commerce::Product Video::Product Review Video": "ProdutoDetalhes",
  "e-commerce::Amazon::Amazon A+ Content": "LandingProduto",
  "e-commerce::Amazon::Amazon Storefront": "LandingProduto",
  "e-commerce::Marketplace::Mercado Livre Banner": "BannerPromocao",
  "e-commerce::Marketplace::Shopee Product Image": "ProdutoDetalhes",
  "e-commerce::Marketplace::AliExpress Product Gallery": "ProdutoDetalhes",
  "conteudo-editorial::Blog::Blog Post Featured Image": "PostBlog",
  "conteudo-editorial::Blog::Blog Post Infographic": "PostBlog",
  "conteudo-editorial::E-book::E-book Cover": "EbookCapa",
  "conteudo-editorial::E-book::E-book Interior Layout": "EbookCapitulo",
  "conteudo-editorial::Whitepaper::Whitepaper Cover": "CaseStudy",
  "conteudo-editorial::Whitepaper::Whitepaper Interior": "CaseStudy",
  "conteudo-editorial::Case Study::Case Study Cover": "CaseStudy",
  "conteudo-editorial::Case Study::Case Study Interior": "CaseStudy",
  "conteudo-editorial::Newsletter::Newsletter Header": "NewsletterCampanha",
  "conteudo-editorial::Newsletter::Newsletter Template": "NewsletterCampanha",
  "educacional::Curso Online::Course Thumbnail": "SlideAulaCapa",
  "educacional::Curso Online::Module Cover": "SlideResumo",
  "educacional::Curso Online::Lesson Slide": "SlideConteudo",
  "educacional::Curso Online::Quiz Screen": "SlideQuiz",
  "educacional::Certificado::Certificate of Completion": "Certificado",
  "educacional::Material Didático::Workbook Cover": "Workbook",
  "educacional::Material Didático::Workbook Interior": "Workbook",
  "educacional::Material Didático::Cheat Sheet": "GuiaRapido",
  "educacional::Vídeo Aula::Video Lesson Intro": "SlideConteudo",
  "educacional::Vídeo Aula::Video Lesson Outro": "SlideConteudo",
  "streaming-podcast::Podcast::Podcast Cover Art": "SpotifyPodcast",
  "streaming-podcast::Podcast::Episode Cover Art": "SpotifyPodcast",
  "streaming-podcast::Podcast::Audiogram": "SpotifyPodcast",
  "streaming-podcast::Podcast::Video Podcast Thumbnail": "YouTubeThumbnail",
  "streaming-podcast::Streaming::Twitch Overlay": "TwitchStream",
  "streaming-podcast::Streaming::Twitch Panel": "TwitchProfile",
  "streaming-podcast::Streaming::YouTube Thumbnail": "YouTubeThumbnail",
  "streaming-podcast::Streaming::YouTube Banner": "YouTubeBanner",
  "streaming-podcast::Streaming::Stream Starting Soon Screen": "TwitchStream",
  "streaming-podcast::Streaming::Stream Ending Screen": "TwitchStream",
};
