import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

export type MockupComponent = ComponentType<any>;

const registry: Record<string, MockupComponent> = {
  "abrigoonibus": dynamic(() => import("./library/midia-off/AbrigoOnibus").then((mod) => mod.AbrigoOnibus)),
  "abrigoonibusbacklight": dynamic(() => import("./library/midia-off/AbrigoOnibusBacklight").then((mod) => mod.AbrigoOnibusBacklight)),
  "adesivoparedeexterno": dynamic(() => import("./library/eventos-ativacoes/AdesivoParedeExterno").then((mod) => mod.AdesivoParedeExterno)),
  "adesivoparedeinterno": dynamic(() => import("./library/eventos-ativacoes/AdesivoParedeInterno").then((mod) => mod.AdesivoParedeInterno)),
  "adesivopiso": dynamic(() => import("./library/eventos-ativacoes/AdesivoPiso").then((mod) => mod.AdesivoPiso)),
  "adesivopisointerno": dynamic(() => import("./library/eventos-ativacoes/AdesivoPisoInterno").then((mod) => mod.AdesivoPisoInterno)),
  "adesivoprateleira": dynamic(() => import("./library/eventos-ativacoes/AdesivoPrateleira").then((mod) => mod.AdesivoPrateleira)),
  "adesivovidro": dynamic(() => import("./library/eventos-ativacoes/AdesivoVidro").then((mod) => mod.AdesivoVidro)),
  "aeroportobacklight": dynamic(() => import("./library/midia-off/AeroportoBacklight").then((mod) => mod.AeroportoBacklight)),
  "aeroportobridge": dynamic(() => import("./library/midia-off/AeroportoBridge").then((mod) => mod.AeroportoBridge)),
  "aeroportocarrinho": dynamic(() => import("./library/midia-off/AeroportoCarrinho").then((mod) => mod.AeroportoCarrinho)),
  "aeroportoesteira": dynamic(() => import("./library/midia-off/AeroportoEsteira").then((mod) => mod.AeroportoEsteira)),
  "aeroportofloorgraphics": dynamic(() => import("./library/midia-off/AeroportoFloorGraphics").then((mod) => mod.AeroportoFloorGraphics)),
  "aeroportolounge": dynamic(() => import("./library/midia-off/AeroportoLounge").then((mod) => mod.AeroportoLounge)),
  "aeroportopainel": dynamic(() => import("./library/midia-off/AeroportoPainel").then((mod) => mod.AeroportoPainel)),
  "aeroportototem": dynamic(() => import("./library/midia-off/AeroportoTotem").then((mod) => mod.AeroportoTotem)),
  "agenda": dynamic(() => import("./library/eventos-ativacoes/Agenda").then((mod) => mod.Agenda)),
  "apostilacapa": dynamic(() => import("./library/educacional/ApostilaCapa").then((mod) => mod.ApostilaCapa)),
  "apostilaexercicios": dynamic(() => import("./library/educacional/ApostilaExercicios").then((mod) => mod.ApostilaExercicios)),
  "apostilagabarito": dynamic(() => import("./library/educacional/ApostilaGabarito").then((mod) => mod.ApostilaGabarito)),
  "apostilapagina": dynamic(() => import("./library/educacional/ApostilaPagina").then((mod) => mod.ApostilaPagina)),
  "arcoentrada": dynamic(() => import("./library/eventos-ativacoes/ArcoEntrada").then((mod) => mod.ArcoEntrada)),
  "areademonstracao": dynamic(() => import("./library/eventos-ativacoes/AreaDemonstracao").then((mod) => mod.AreaDemonstracao)),
  "arealounge": dynamic(() => import("./library/eventos-ativacoes/AreaLounge").then((mod) => mod.AreaLounge)),
  "areapromocional": dynamic(() => import("./library/eventos-ativacoes/AreaPromocional").then((mod) => mod.AreaPromocional)),
  "artigolongo": dynamic(() => import("./library/conteudo-editorial/ArtigoLongo").then((mod) => mod.ArtigoLongo)),
  "assinaturaemail": dynamic(() => import("./library/branding/AssinaturaEmail").then((mod) => mod.AssinaturaEmail)),
  "atividade": dynamic(() => import("./library/educacional/Atividade").then((mod) => mod.Atividade)),
  "avaliacao": dynamic(() => import("./library/educacional/Avaliacao").then((mod) => mod.Avaliacao)),
  "backdroppalco": dynamic(() => import("./library/eventos-ativacoes/BackdropPalco").then((mod) => mod.BackdropPalco)),
  "badge": dynamic(() => import("./library/educacional/Badge").then((mod) => mod.Badge)),
  "bancajornal": dynamic(() => import("./library/midia-off/BancaJornal").then((mod) => mod.BancaJornal)),
  "bancopublicitario": dynamic(() => import("./library/midia-off/BancoPublicitario").then((mod) => mod.BancoPublicitario)),
  "bandeiravento": dynamic(() => import("./library/eventos-ativacoes/BandeiraVento").then((mod) => mod.BandeiraVento)),
  "bannerapp": dynamic(() => import("./library/ecommerce/BannerApp").then((mod) => mod.BannerApp)),
  "bannerblackfriday": dynamic(() => import("./library/ecommerce/BannerBlackFriday").then((mod) => mod.BannerBlackFriday)),
  "bannercategoria": dynamic(() => import("./library/ecommerce/BannerCategoria").then((mod) => mod.BannerCategoria)),
  "bannercountdown": dynamic(() => import("./library/ecommerce/BannerCountdown").then((mod) => mod.BannerCountdown)),
  "bannerdesconto": dynamic(() => import("./library/ecommerce/BannerDesconto").then((mod) => mod.BannerDesconto)),
  "bannerfretegratis": dynamic(() => import("./library/ecommerce/BannerFreteGratis").then((mod) => mod.BannerFreteGratis)),
  "bannerhero": dynamic(() => import("./library/ecommerce/BannerHero").then((mod) => mod.BannerHero)),
  "bannerlancamento": dynamic(() => import("./library/ecommerce/BannerLancamento").then((mod) => mod.BannerLancamento)),
  "bannernewsletter": dynamic(() => import("./library/ecommerce/BannerNewsletter").then((mod) => mod.BannerNewsletter)),
  "bannerpromocao": dynamic(() => import("./library/ecommerce/BannerPromocao").then((mod) => mod.BannerPromocao)),
  "behanceprofile": dynamic(() => import("./library/social-batch2/BehanceProfile").then((mod) => mod.BehanceProfile)),
  "behanceproject": dynamic(() => import("./library/social-batch2/BehanceProject").then((mod) => mod.BehanceProject)),
  "bicicletariopublicitario": dynamic(() => import("./library/midia-off/BicicletarioPublicitario").then((mod) => mod.BicicletarioPublicitario)),
  "bone": dynamic(() => import("./library/eventos-ativacoes/Bone").then((mod) => mod.Bone)),
  "brandbookaplicacoes": dynamic(() => import("./library/branding/BrandbookAplicacoes").then((mod) => mod.BrandbookAplicacoes)),
  "brandbookcapa": dynamic(() => import("./library/branding/BrandbookCapa").then((mod) => mod.BrandbookCapa)),
  "brandbookcores": dynamic(() => import("./library/branding/BrandbookCores").then((mod) => mod.BrandbookCores)),
  "brandbookdiretrizes": dynamic(() => import("./library/branding/BrandbookDiretrizes").then((mod) => mod.BrandbookDiretrizes)),
  "brandbookiconografia": dynamic(() => import("./library/branding/BrandbookIconografia").then((mod) => mod.BrandbookIconografia)),
  "brandbooklogo": dynamic(() => import("./library/branding/BrandbookLogo").then((mod) => mod.BrandbookLogo)),
  "brandbookpadrao": dynamic(() => import("./library/branding/BrandbookPadrao").then((mod) => mod.BrandbookPadrao)),
  "brandbooktipografia": dynamic(() => import("./library/branding/BrandbookTipografia").then((mod) => mod.BrandbookTipografia)),
  "buscaprodutos": dynamic(() => import("./library/ecommerce/BuscaProdutos").then((mod) => mod.BuscaProdutos)),
  "cabinetelefonica": dynamic(() => import("./library/midia-off/CabineTelefonica").then((mod) => mod.CabineTelefonica)),
  "caderno": dynamic(() => import("./library/eventos-ativacoes/Caderno").then((mod) => mod.Caderno)),
  "camiseta": dynamic(() => import("./library/eventos-ativacoes/Camiseta").then((mod) => mod.Camiseta)),
  "caneta": dynamic(() => import("./library/eventos-ativacoes/Caneta").then((mod) => mod.Caneta)),
  "caparedes": dynamic(() => import("./library/branding/CapaRedes").then((mod) => mod.CapaRedes)),
  "carrinhocompras": dynamic(() => import("./library/ecommerce/CarrinhoCompras").then((mod) => mod.CarrinhoCompras)),
  "cartaovisita": dynamic(() => import("./library/branding/CartaoVisita").then((mod) => mod.CartaoVisita)),
  "casestudy": dynamic(() => import("./library/conteudo-editorial/CaseStudy").then((mod) => mod.CaseStudy)),
  "categoriaprodutos": dynamic(() => import("./library/ecommerce/CategoriaProdutos").then((mod) => mod.CategoriaProdutos)),
  "cavaletecalcada": dynamic(() => import("./library/eventos-ativacoes/CavaleteCalcada").then((mod) => mod.CavaleteCalcada)),
  "certificado": dynamic(() => import("./library/educacional/Certificado").then((mod) => mod.Certificado)),
  "chaveiro": dynamic(() => import("./library/eventos-ativacoes/Chaveiro").then((mod) => mod.Chaveiro)),
  "checklist": dynamic(() => import("./library/educacional/Checklist").then((mod) => mod.Checklist)),
  "checkout": dynamic(() => import("./library/ecommerce/Checkout").then((mod) => mod.Checkout)),
  "checkstand": dynamic(() => import("./library/eventos-ativacoes/CheckStand").then((mod) => mod.CheckStand)),
  "clipstrip": dynamic(() => import("./library/eventos-ativacoes/Clipstrip").then((mod) => mod.Clipstrip)),
  "colunapublicidade": dynamic(() => import("./library/midia-off/ColunaPublicidade").then((mod) => mod.ColunaPublicidade)),
  "comparacaoprodutos": dynamic(() => import("./library/ecommerce/ComparacaoProdutos").then((mod) => mod.ComparacaoProdutos)),
  "copo": dynamic(() => import("./library/eventos-ativacoes/Copo").then((mod) => mod.Copo)),
  "demonstrador": dynamic(() => import("./library/eventos-ativacoes/Demonstrador").then((mod) => mod.Demonstrador)),
  "diploma": dynamic(() => import("./library/educacional/Diploma").then((mod) => mod.Diploma)),
  "discordembed": dynamic(() => import("./library/social-batch2/DiscordEmbed").then((mod) => mod.DiscordEmbed)),
  "discordmessage": dynamic(() => import("./library/social-batch2/DiscordMessage").then((mod) => mod.DiscordMessage)),
  "discordserver": dynamic(() => import("./library/social-batch2/DiscordServer").then((mod) => mod.DiscordServer)),
  "displaybalcao": dynamic(() => import("./library/eventos-ativacoes/DisplayBalcao").then((mod) => mod.DisplayBalcao)),
  "displaychao": dynamic(() => import("./library/eventos-ativacoes/DisplayChao").then((mod) => mod.DisplayChao)),
  "displayproduto": dynamic(() => import("./library/eventos-ativacoes/DisplayProduto").then((mod) => mod.DisplayProduto)),
  "dribbbleprofile": dynamic(() => import("./library/social-batch2/DribbbleProfile").then((mod) => mod.DribbbleProfile)),
  "dribbbleshot": dynamic(() => import("./library/social-batch2/DribbbleShot").then((mod) => mod.DribbbleShot)),
  "ebookcapa": dynamic(() => import("./library/educacional/EbookCapa").then((mod) => mod.EbookCapa)),
  "ebookcapitulo": dynamic(() => import("./library/educacional/EbookCapitulo").then((mod) => mod.EbookCapitulo)),
  "ebookcitacao": dynamic(() => import("./library/educacional/EbookCitacao").then((mod) => mod.EbookCitacao)),
  "ebookdestaque": dynamic(() => import("./library/educacional/EbookDestaque").then((mod) => mod.EbookDestaque)),
  "ebookindice": dynamic(() => import("./library/educacional/EbookIndice").then((mod) => mod.EbookIndice)),
  "ecobag": dynamic(() => import("./library/eventos-ativacoes/Ecobag").then((mod) => mod.Ecobag)),
  "entrevista": dynamic(() => import("./library/conteudo-editorial/Entrevista").then((mod) => mod.Entrevista)),
  "envelope": dynamic(() => import("./library/branding/Envelope").then((mod) => mod.Envelope)),
  "estandearco": dynamic(() => import("./library/eventos-ativacoes/EstandeArco").then((mod) => mod.EstandeArco)),
  "estandebackwall": dynamic(() => import("./library/eventos-ativacoes/EstandeBackwall").then((mod) => mod.EstandeBackwall)),
  "estandebalcao": dynamic(() => import("./library/eventos-ativacoes/EstandeBalcao").then((mod) => mod.EstandeBalcao)),
  "estandebanner": dynamic(() => import("./library/eventos-ativacoes/EstandeBanner").then((mod) => mod.EstandeBanner)),
  "estandecubo": dynamic(() => import("./library/eventos-ativacoes/EstandeCubo").then((mod) => mod.EstandeCubo)),
  "estandegrande": dynamic(() => import("./library/eventos-ativacoes/EstandeGrande").then((mod) => mod.EstandeGrande)),
  "estandeilha": dynamic(() => import("./library/eventos-ativacoes/EstandeIlha").then((mod) => mod.EstandeIlha)),
  "estandelbanner": dynamic(() => import("./library/eventos-ativacoes/EstandeLBanner").then((mod) => mod.EstandeLBanner)),
  "estandemedio": dynamic(() => import("./library/eventos-ativacoes/EstandeMedio").then((mod) => mod.EstandeMedio)),
  "estandemesa": dynamic(() => import("./library/eventos-ativacoes/EstandeMesa").then((mod) => mod.EstandeMesa)),
  "estandepequeno": dynamic(() => import("./library/eventos-ativacoes/EstandePequeno").then((mod) => mod.EstandePequeno)),
  "estandeponta": dynamic(() => import("./library/eventos-ativacoes/EstandePonta").then((mod) => mod.EstandePonta)),
  "estandetenda": dynamic(() => import("./library/eventos-ativacoes/EstandeTenda").then((mod) => mod.EstandeTenda)),
  "estandetotem": dynamic(() => import("./library/eventos-ativacoes/EstandeTotem").then((mod) => mod.EstandeTotem)),
  "estandexbanner": dynamic(() => import("./library/eventos-ativacoes/EstandeXBanner").then((mod) => mod.EstandeXBanner)),
  "estruturasuspensa": dynamic(() => import("./library/eventos-ativacoes/EstruturaSuspensa").then((mod) => mod.EstruturaSuspensa)),
  "expositor": dynamic(() => import("./library/eventos-ativacoes/Expositor").then((mod) => mod.Expositor)),
  "facebookad": dynamic(() => import("./library/social/FacebookAd").then((mod) => mod.FacebookAd)),
  "facebookcarousel": dynamic(() => import("./library/social/FacebookCarousel").then((mod) => mod.FacebookCarousel)),
  "facebookcover": dynamic(() => import("./library/social/FacebookCover").then((mod) => mod.FacebookCover)),
  "facebookevent": dynamic(() => import("./library/midia-on/FacebookEvent").then((mod) => mod.FacebookEvent)),
  "facebookgroup": dynamic(() => import("./library/midia-on/FacebookGroup").then((mod) => mod.FacebookGroup)),
  "facebookmarketplace": dynamic(() => import("./library/midia-on/FacebookMarketplace").then((mod) => mod.FacebookMarketplace)),
  "facebookmemory": dynamic(() => import("./library/midia-on/FacebookMemory").then((mod) => mod.FacebookMemory)),
  "facebookpoll": dynamic(() => import("./library/midia-on/FacebookPoll").then((mod) => mod.FacebookPoll)),
  "facebookpost": dynamic(() => import("./library/social/FacebookPost").then((mod) => mod.FacebookPost)),
  "facebookstory": dynamic(() => import("./library/social/FacebookStory").then((mod) => mod.FacebookStory)),
  "facebookwatch": dynamic(() => import("./library/midia-on/FacebookWatch").then((mod) => mod.FacebookWatch)),
  "faixafachada": dynamic(() => import("./library/eventos-ativacoes/FaixaFachada").then((mod) => mod.FaixaFachada)),
  "faixagondola": dynamic(() => import("./library/eventos-ativacoes/FaixaGondola").then((mod) => mod.FaixaGondola)),
  "faq": dynamic(() => import("./library/conteudo-editorial/FAQ").then((mod) => mod.FAQ)),
  "filtrosprodutos": dynamic(() => import("./library/ecommerce/FiltrosProdutos").then((mod) => mod.FiltrosProdutos)),
  "flashcard": dynamic(() => import("./library/educacional/Flashcard").then((mod) => mod.Flashcard)),
  "floralpublicitario": dynamic(() => import("./library/midia-off/FloralPublicitario").then((mod) => mod.FloralPublicitario)),
  "googlebanner160x600": dynamic(() => import("./library/midia-on/GoogleBanner160x600").then((mod) => mod.GoogleBanner160x600)),
  "googlebanner300x250": dynamic(() => import("./library/midia-on/GoogleBanner300x250").then((mod) => mod.GoogleBanner300x250)),
  "googlebanner300x600": dynamic(() => import("./library/midia-on/GoogleBanner300x600").then((mod) => mod.GoogleBanner300x600)),
  "googlebanner728x90": dynamic(() => import("./library/midia-on/GoogleBanner728x90").then((mod) => mod.GoogleBanner728x90)),
  "googlebanner970x250": dynamic(() => import("./library/midia-on/GoogleBanner970x250").then((mod) => mod.GoogleBanner970x250)),
  "googledisplayad": dynamic(() => import("./library/social/GoogleDisplayAd").then((mod) => mod.GoogleDisplayAd)),
  "googleinterstitial": dynamic(() => import("./library/midia-on/GoogleInterstitial").then((mod) => mod.GoogleInterstitial)),
  "googlemybusiness": dynamic(() => import("./library/midia-on/GoogleMyBusiness").then((mod) => mod.GoogleMyBusiness)),
  "googlenativead": dynamic(() => import("./library/midia-on/GoogleNativeAd").then((mod) => mod.GoogleNativeAd)),
  "googleresponsivead": dynamic(() => import("./library/midia-on/GoogleResponsiveAd").then((mod) => mod.GoogleResponsiveAd)),
  "googlereview": dynamic(() => import("./library/midia-on/GoogleReview").then((mod) => mod.GoogleReview)),
  "googlesearchad": dynamic(() => import("./library/social/GoogleSearchAd").then((mod) => mod.GoogleSearchAd)),
  "googleshoppingad": dynamic(() => import("./library/social/GoogleShoppingAd").then((mod) => mod.GoogleShoppingAd)),
  "googlevideoad": dynamic(() => import("./library/social/GoogleVideoAd").then((mod) => mod.GoogleVideoAd)),
  "gradeprotecao": dynamic(() => import("./library/midia-off/GradeProtecao").then((mod) => mod.GradeProtecao)),
  "guardachuva": dynamic(() => import("./library/eventos-ativacoes/GuardaChuva").then((mod) => mod.GuardaChuva)),
  "guiacompleto": dynamic(() => import("./library/conteudo-editorial/GuiaCompleto").then((mod) => mod.GuiaCompleto)),
  "guiarapido": dynamic(() => import("./library/educacional/GuiaRapido").then((mod) => mod.GuiaRapido)),
  "infograficocomparacao": dynamic(() => import("./library/conteudo-editorial/InfograficoComparacao").then((mod) => mod.InfograficoComparacao)),
  "infograficodados": dynamic(() => import("./library/conteudo-editorial/InfograficoDados").then((mod) => mod.InfograficoDados)),
  "infograficoeducativo": dynamic(() => import("./library/educacional/InfograficoEducativo").then((mod) => mod.InfograficoEducativo)),
  "infograficoestatisticas": dynamic(() => import("./library/conteudo-editorial/InfograficoEstatisticas").then((mod) => mod.InfograficoEstatisticas)),
  "infograficohierarquia": dynamic(() => import("./library/conteudo-editorial/InfograficoHierarquia").then((mod) => mod.InfograficoHierarquia)),
  "infograficomapa": dynamic(() => import("./library/conteudo-editorial/InfograficoMapa").then((mod) => mod.InfograficoMapa)),
  "infograficoprocesso": dynamic(() => import("./library/conteudo-editorial/InfograficoProcesso").then((mod) => mod.InfograficoProcesso)),
  "infograficotimeline": dynamic(() => import("./library/conteudo-editorial/InfograficoTimeline").then((mod) => mod.InfograficoTimeline)),
  "infograficovertical": dynamic(() => import("./library/conteudo-editorial/InfograficoVertical").then((mod) => mod.InfograficoVertical)),
  "instagramad": dynamic(() => import("./library/midia-on/InstagramAd").then((mod) => mod.InstagramAd)),
  "instagramcarousel": dynamic(() => import("./library/midia-on/InstagramCarousel").then((mod) => mod.InstagramCarousel)),
  "instagramlive": dynamic(() => import("./library/midia-on/InstagramLive").then((mod) => mod.InstagramLive)),
  "instagramreel": dynamic(() => import("./library/midia-on/InstagramReel").then((mod) => mod.InstagramReel)),
  "jornalcaderno": dynamic(() => import("./library/midia-off/JornalCaderno").then((mod) => mod.JornalCaderno)),
  "jornalclassificado": dynamic(() => import("./library/midia-off/JornalClassificado").then((mod) => mod.JornalClassificado)),
  "jornalcoluna": dynamic(() => import("./library/midia-off/JornalColuna").then((mod) => mod.JornalColuna)),
  "jornalcupom": dynamic(() => import("./library/midia-off/JornalCupom").then((mod) => mod.JornalCupom)),
  "jornaldestaque": dynamic(() => import("./library/midia-off/JornalDestaque").then((mod) => mod.JornalDestaque)),
  "jornalduplex": dynamic(() => import("./library/midia-off/JornalDuplex").then((mod) => mod.JornalDuplex)),
  "jornalencarte": dynamic(() => import("./library/midia-off/JornalEncarte").then((mod) => mod.JornalEncarte)),
  "jornalfaixa": dynamic(() => import("./library/midia-off/JornalFaixa").then((mod) => mod.JornalFaixa)),
  "jornalilhote": dynamic(() => import("./library/midia-off/JornalIlhote").then((mod) => mod.JornalIlhote)),
  "jornalinforme": dynamic(() => import("./library/midia-off/JornalInforme").then((mod) => mod.JornalInforme)),
  "jornalmeiapagina": dynamic(() => import("./library/midia-off/JornalMeiaPagina").then((mod) => mod.JornalMeiaPagina)),
  "jornalnecrologia": dynamic(() => import("./library/midia-off/JornalNecrologia").then((mod) => mod.JornalNecrologia)),
  "jornalorelha": dynamic(() => import("./library/midia-off/JornalOrelha").then((mod) => mod.JornalOrelha)),
  "jornalpaginainteira": dynamic(() => import("./library/midia-off/JornalPaginaInteira").then((mod) => mod.JornalPaginaInteira)),
  "jornalprimeirapagina": dynamic(() => import("./library/midia-off/JornalPrimeiraPagina").then((mod) => mod.JornalPrimeiraPagina)),
  "jornalquartopagina": dynamic(() => import("./library/midia-off/JornalQuartoPagina").then((mod) => mod.JornalQuartoPagina)),
  "jornalrodape": dynamic(() => import("./library/midia-off/JornalRodape").then((mod) => mod.JornalRodape)),
  "jornalsuplemento": dynamic(() => import("./library/midia-off/JornalSuplemento").then((mod) => mod.JornalSuplemento)),
  "jornaltriplex": dynamic(() => import("./library/midia-off/JornalTriplex").then((mod) => mod.JornalTriplex)),
  "jornalultimapagina": dynamic(() => import("./library/midia-off/JornalUltimaPagina").then((mod) => mod.JornalUltimaPagina)),
  "keynoteagenda": dynamic(() => import("./library/apresentacoes/KeynoteAgenda").then((mod) => mod.KeynoteAgenda)),
  "keynotecapa": dynamic(() => import("./library/apresentacoes/KeynoteCapa").then((mod) => mod.KeynoteCapa)),
  "keynotecitacao": dynamic(() => import("./library/apresentacoes/KeynoteCitacao").then((mod) => mod.KeynoteCitacao)),
  "keynotecomparacao": dynamic(() => import("./library/apresentacoes/KeynoteComparacao").then((mod) => mod.KeynoteComparacao)),
  "keynoteconteudo": dynamic(() => import("./library/apresentacoes/KeynoteConteudo").then((mod) => mod.KeynoteConteudo)),
  "keynotecta": dynamic(() => import("./library/apresentacoes/KeynoteCTA").then((mod) => mod.KeynoteCTA)),
  "keynotedados": dynamic(() => import("./library/apresentacoes/KeynoteDados").then((mod) => mod.KeynoteDados)),
  "keynotegrafico": dynamic(() => import("./library/apresentacoes/KeynoteGrafico").then((mod) => mod.KeynoteGrafico)),
  "keynoteimagem": dynamic(() => import("./library/apresentacoes/KeynoteImagem").then((mod) => mod.KeynoteImagem)),
  "keynoteintroducao": dynamic(() => import("./library/apresentacoes/KeynoteIntroducao").then((mod) => mod.KeynoteIntroducao)),
  "keynoteobrigado": dynamic(() => import("./library/apresentacoes/KeynoteObrigado").then((mod) => mod.KeynoteObrigado)),
  "keynoteperguntas": dynamic(() => import("./library/apresentacoes/KeynotePerguntas").then((mod) => mod.KeynotePerguntas)),
  "keynoteresumo": dynamic(() => import("./library/apresentacoes/KeynoteResumo").then((mod) => mod.KeynoteResumo)),
  "keynotetimeline": dynamic(() => import("./library/apresentacoes/KeynoteTimeline").then((mod) => mod.KeynoteTimeline)),
  "keynotetopico": dynamic(() => import("./library/apresentacoes/KeynoteTopico").then((mod) => mod.KeynoteTopico)),
  "kitescritorio": dynamic(() => import("./library/eventos-ativacoes/KitEscritorio").then((mod) => mod.KitEscritorio)),
  "landingcampanha": dynamic(() => import("./library/ecommerce/LandingCampanha").then((mod) => mod.LandingCampanha)),
  "landingcolecao": dynamic(() => import("./library/ecommerce/LandingColecao").then((mod) => mod.LandingColecao)),
  "landingfidelidade": dynamic(() => import("./library/ecommerce/LandingFidelidade").then((mod) => mod.LandingFidelidade)),
  "landinggiftcard": dynamic(() => import("./library/ecommerce/LandingGiftCard").then((mod) => mod.LandingGiftCard)),
  "landinglancamento": dynamic(() => import("./library/ecommerce/LandingLancamento").then((mod) => mod.LandingLancamento)),
  "landingmarca": dynamic(() => import("./library/ecommerce/LandingMarca").then((mod) => mod.LandingMarca)),
  "landingoferta": dynamic(() => import("./library/ecommerce/LandingOferta").then((mod) => mod.LandingOferta)),
  "landingprevenda": dynamic(() => import("./library/ecommerce/LandingPreVenda").then((mod) => mod.LandingPreVenda)),
  "landingproduto": dynamic(() => import("./library/ecommerce/LandingProduto").then((mod) => mod.LandingProduto)),
  "landingthankyou": dynamic(() => import("./library/ecommerce/LandingThankYou").then((mod) => mod.LandingThankYou)),
  "letreirocaixa": dynamic(() => import("./library/eventos-ativacoes/LetreiroCaixa").then((mod) => mod.LetreiroCaixa)),
  "letreirorecorte": dynamic(() => import("./library/eventos-ativacoes/LetreiroRecorte").then((mod) => mod.LetreiroRecorte)),
  "linhadotempo": dynamic(() => import("./library/educacional/LinhaDoTempo").then((mod) => mod.LinhaDoTempo)),
  "linkedinad": dynamic(() => import("./library/social/LinkedInAd").then((mod) => mod.LinkedInAd)),
  "linkedinarticle": dynamic(() => import("./library/social/LinkedInArticle").then((mod) => mod.LinkedInArticle)),
  "linkedincertificate": dynamic(() => import("./library/midia-on/LinkedInCertificate").then((mod) => mod.LinkedInCertificate)),
  "linkedinevent": dynamic(() => import("./library/midia-on/LinkedInEvent").then((mod) => mod.LinkedInEvent)),
  "linkedinjobpost": dynamic(() => import("./library/midia-on/LinkedInJobPost").then((mod) => mod.LinkedInJobPost)),
  "linkedinnewsletter": dynamic(() => import("./library/midia-on/LinkedInNewsletter").then((mod) => mod.LinkedInNewsletter)),
  "linkedinpoll": dynamic(() => import("./library/midia-on/LinkedInPoll").then((mod) => mod.LinkedInPoll)),
  "linkedinpost": dynamic(() => import("./library/social/LinkedInPost").then((mod) => mod.LinkedInPost)),
  "linkedinprofile": dynamic(() => import("./library/social/LinkedInProfile").then((mod) => mod.LinkedInProfile)),
  "linkedinrecommendation": dynamic(() => import("./library/midia-on/LinkedInRecommendation").then((mod) => mod.LinkedInRecommendation)),
  "listaprodutos": dynamic(() => import("./library/ecommerce/ListaProdutos").then((mod) => mod.ListaProdutos)),
  "listicle": dynamic(() => import("./library/conteudo-editorial/Listicle").then((mod) => mod.Listicle)),
  "lixeirapublicitaria": dynamic(() => import("./library/midia-off/LixeiraPublicitaria").then((mod) => mod.LixeiraPublicitaria)),
  "logofavicon": dynamic(() => import("./library/branding/LogoFavicon").then((mod) => mod.LogoFavicon)),
  "logohorizontal": dynamic(() => import("./library/branding/LogoHorizontal").then((mod) => mod.LogoHorizontal)),
  "logoicone": dynamic(() => import("./library/branding/LogoIcone").then((mod) => mod.LogoIcone)),
  "logominimo": dynamic(() => import("./library/branding/LogoMinimo").then((mod) => mod.LogoMinimo)),
  "logomonocromatico": dynamic(() => import("./library/branding/LogoMonocromatico").then((mod) => mod.LogoMonocromatico)),
  "logonegativo": dynamic(() => import("./library/branding/LogoNegativo").then((mod) => mod.LogoNegativo)),
  "logoprincipal": dynamic(() => import("./library/branding/LogoPrincipal").then((mod) => mod.LogoPrincipal)),
  "logovariacoes": dynamic(() => import("./library/branding/LogoVariacoes").then((mod) => mod.LogoVariacoes)),
  "logovertical": dynamic(() => import("./library/branding/LogoVertical").then((mod) => mod.LogoVertical)),
  "logowatermark": dynamic(() => import("./library/branding/LogoWatermark").then((mod) => mod.LogoWatermark)),
  "manualcolaborador": dynamic(() => import("./library/endomarketing/ManualColaborador").then((mod) => mod.ManualColaborador)),
  "manualintegracao": dynamic(() => import("./library/endomarketing/ManualIntegracao").then((mod) => mod.ManualIntegracao)),
  "manualprocedimentos": dynamic(() => import("./library/endomarketing/ManualProcedimentos").then((mod) => mod.ManualProcedimentos)),
  "manualqualidade": dynamic(() => import("./library/endomarketing/ManualQualidade").then((mod) => mod.ManualQualidade)),
  "manualseguranca": dynamic(() => import("./library/endomarketing/ManualSeguranca").then((mod) => mod.ManualSeguranca)),
  "mapamental": dynamic(() => import("./library/educacional/MapaMental").then((mod) => mod.MapaMental)),
  "mediakitcapa": dynamic(() => import("./library/conteudo-editorial/MediaKitCapa").then((mod) => mod.MediaKitCapa)),
  "mediakitconteudo": dynamic(() => import("./library/conteudo-editorial/MediaKitConteudo").then((mod) => mod.MediaKitConteudo)),
  "mediumarticle": dynamic(() => import("./library/social-batch2/MediumArticle").then((mod) => mod.MediumArticle)),
  "mediumprofile": dynamic(() => import("./library/social-batch2/MediumProfile").then((mod) => mod.MediumProfile)),
  "metroadesivo": dynamic(() => import("./library/midia-off/MetroAdesivo").then((mod) => mod.MetroAdesivo)),
  "metrobacklight": dynamic(() => import("./library/midia-off/MetroBacklight").then((mod) => mod.MetroBacklight)),
  "metroescada": dynamic(() => import("./library/midia-off/MetroEscada").then((mod) => mod.MetroEscada)),
  "metropainel": dynamic(() => import("./library/midia-off/MetroPainel").then((mod) => mod.MetroPainel)),
  "metroplataforma": dynamic(() => import("./library/midia-off/MetroPlataforma").then((mod) => mod.MetroPlataforma)),
  "metroteto": dynamic(() => import("./library/midia-off/MetroTeto").then((mod) => mod.MetroTeto)),
  "metrotunel": dynamic(() => import("./library/midia-off/MetroTunel").then((mod) => mod.MetroTunel)),
  "mochila": dynamic(() => import("./library/eventos-ativacoes/Mochila").then((mod) => mod.Mochila)),
  "mousepad": dynamic(() => import("./library/eventos-ativacoes/MousePad").then((mod) => mod.MousePad)),
  "newsletteraniversariantes": dynamic(() => import("./library/endomarketing/NewsletterAniversariantes").then((mod) => mod.NewsletterAniversariantes)),
  "newsletterbeneficios": dynamic(() => import("./library/endomarketing/NewsletterBeneficios").then((mod) => mod.NewsletterBeneficios)),
  "newslettercampanha": dynamic(() => import("./library/endomarketing/NewsletterCampanha").then((mod) => mod.NewsletterCampanha)),
  "newsletterceo": dynamic(() => import("./library/endomarketing/NewsletterCEO").then((mod) => mod.NewsletterCEO)),
  "newslettereventos": dynamic(() => import("./library/endomarketing/NewsletterEventos").then((mod) => mod.NewsletterEventos)),
  "newsletterinovacao": dynamic(() => import("./library/endomarketing/NewsletterInovacao").then((mod) => mod.NewsletterInovacao)),
  "newslettermensal": dynamic(() => import("./library/endomarketing/NewsletterMensal").then((mod) => mod.NewsletterMensal)),
  "newsletternovosfuncionarios": dynamic(() => import("./library/endomarketing/NewsletterNovosFuncionarios").then((mod) => mod.NewsletterNovosFuncionarios)),
  "newsletterresultados": dynamic(() => import("./library/endomarketing/NewsletterResultados").then((mod) => mod.NewsletterResultados)),
  "newsletterrh": dynamic(() => import("./library/endomarketing/NewsletterRH").then((mod) => mod.NewsletterRH)),
  "newsletterseguranca": dynamic(() => import("./library/endomarketing/NewsletterSeguranca").then((mod) => mod.NewsletterSeguranca)),
  "newslettersemanal": dynamic(() => import("./library/endomarketing/NewsletterSemanal").then((mod) => mod.NewsletterSemanal)),
  "newslettersustentabilidade": dynamic(() => import("./library/endomarketing/NewsletterSustentabilidade").then((mod) => mod.NewsletterSustentabilidade)),
  "newslettertreinamentos": dynamic(() => import("./library/endomarketing/NewsletterTreinamentos").then((mod) => mod.NewsletterTreinamentos)),
  "newslettertrimestral": dynamic(() => import("./library/endomarketing/NewsletterTrimestral").then((mod) => mod.NewsletterTrimestral)),
  "noticia": dynamic(() => import("./library/conteudo-editorial/Noticia").then((mod) => mod.Noticia)),
  "outdoor9x3": dynamic(() => import("./library/midia-off/Outdoor9x3").then((mod) => mod.Outdoor9x3)),
  "outdoorbacklight": dynamic(() => import("./library/midia-off/OutdoorBackLight").then((mod) => mod.OutdoorBackLight)),
  "outdoorbusdoor": dynamic(() => import("./library/midia-off/OutdoorBusdoor").then((mod) => mod.OutdoorBusdoor)),
  "outdoordigital": dynamic(() => import("./library/midia-off/OutdoorDigital").then((mod) => mod.OutdoorDigital)),
  "outdoorempena": dynamic(() => import("./library/midia-off/OutdoorEmpena").then((mod) => mod.OutdoorEmpena)),
  "outdoorfrontlight": dynamic(() => import("./library/midia-off/OutdoorFrontLight").then((mod) => mod.OutdoorFrontLight)),
  "outdoorrelogio": dynamic(() => import("./library/midia-off/OutdoorRelogio").then((mod) => mod.OutdoorRelogio)),
  "outdoortaxi": dynamic(() => import("./library/midia-off/OutdoorTaxi").then((mod) => mod.OutdoorTaxi)),
  "outdoortotem": dynamic(() => import("./library/midia-off/OutdoorTotem").then((mod) => mod.OutdoorTotem)),
  "outdoortri": dynamic(() => import("./library/midia-off/OutdoorTri").then((mod) => mod.OutdoorTri)),
  "paineldirecional": dynamic(() => import("./library/eventos-ativacoes/PainelDirecional").then((mod) => mod.PainelDirecional)),
  "painelled": dynamic(() => import("./library/eventos-ativacoes/PainelLED").then((mod) => mod.PainelLED)),
  "palcoevento": dynamic(() => import("./library/eventos-ativacoes/PalcoEvento").then((mod) => mod.PalcoEvento)),
  "papelaria": dynamic(() => import("./library/branding/Papelaria").then((mod) => mod.Papelaria)),
  "passarelapedestre": dynamic(() => import("./library/midia-off/PassarelaPedestre").then((mod) => mod.PassarelaPedestre)),
  "pendrive": dynamic(() => import("./library/eventos-ativacoes/PenDrive").then((mod) => mod.PenDrive)),
  "photobooth": dynamic(() => import("./library/eventos-ativacoes/PhotoBooth").then((mod) => mod.PhotoBooth)),
  "pinterestboard": dynamic(() => import("./library/social/PinterestBoard").then((mod) => mod.PinterestBoard)),
  "pinterestideapin": dynamic(() => import("./library/social/PinterestIdeaPin").then((mod) => mod.PinterestIdeaPin)),
  "pinterestpin": dynamic(() => import("./library/social/PinterestPin").then((mod) => mod.PinterestPin)),
  "pinterestprofile": dynamic(() => import("./library/midia-on/PinterestProfile").then((mod) => mod.PinterestProfile)),
  "pinterestshop": dynamic(() => import("./library/midia-on/PinterestShop").then((mod) => mod.PinterestShop)),
  "pintereststory": dynamic(() => import("./library/midia-on/PinterestStory").then((mod) => mod.PinterestStory)),
  "pinteresttrend": dynamic(() => import("./library/midia-on/PinterestTrend").then((mod) => mod.PinterestTrend)),
  "pitchcapa": dynamic(() => import("./library/apresentacoes/PitchCapa").then((mod) => mod.PitchCapa)),
  "pitchcompetidores": dynamic(() => import("./library/apresentacoes/PitchCompetidores").then((mod) => mod.PitchCompetidores)),
  "pitchcontato": dynamic(() => import("./library/apresentacoes/PitchContato").then((mod) => mod.PitchContato)),
  "pitchfinanceiro": dynamic(() => import("./library/apresentacoes/PitchFinanceiro").then((mod) => mod.PitchFinanceiro)),
  "pitchinvestimento": dynamic(() => import("./library/apresentacoes/PitchInvestimento").then((mod) => mod.PitchInvestimento)),
  "pitchmercado": dynamic(() => import("./library/apresentacoes/PitchMercado").then((mod) => mod.PitchMercado)),
  "pitchmilestones": dynamic(() => import("./library/apresentacoes/PitchMilestones").then((mod) => mod.PitchMilestones)),
  "pitchmodelo": dynamic(() => import("./library/apresentacoes/PitchModelo").then((mod) => mod.PitchModelo)),
  "pitchobrigado": dynamic(() => import("./library/apresentacoes/PitchObrigado").then((mod) => mod.PitchObrigado)),
  "pitchproblema": dynamic(() => import("./library/apresentacoes/PitchProblema").then((mod) => mod.PitchProblema)),
  "pitchproduto": dynamic(() => import("./library/apresentacoes/PitchProduto").then((mod) => mod.PitchProduto)),
  "pitchroadmap": dynamic(() => import("./library/apresentacoes/PitchRoadmap").then((mod) => mod.PitchRoadmap)),
  "pitchsolucao": dynamic(() => import("./library/apresentacoes/PitchSolucao").then((mod) => mod.PitchSolucao)),
  "pitchtime": dynamic(() => import("./library/apresentacoes/PitchTime").then((mod) => mod.PitchTime)),
  "pitchtracao": dynamic(() => import("./library/apresentacoes/PitchTracao").then((mod) => mod.PitchTracao)),
  "placadirecional": dynamic(() => import("./library/eventos-ativacoes/PlacaDirecional").then((mod) => mod.PlacaDirecional)),
  "placaestacionamento": dynamic(() => import("./library/eventos-ativacoes/PlacaEstacionamento").then((mod) => mod.PlacaEstacionamento)),
  "placafachada": dynamic(() => import("./library/eventos-ativacoes/PlacaFachada").then((mod) => mod.PlacaFachada)),
  "placahorario": dynamic(() => import("./library/eventos-ativacoes/PlacaHorario").then((mod) => mod.PlacaHorario)),
  "placaparede": dynamic(() => import("./library/eventos-ativacoes/PlacaParede").then((mod) => mod.PlacaParede)),
  "placaporta": dynamic(() => import("./library/eventos-ativacoes/PlacaPorta").then((mod) => mod.PlacaPorta)),
  "placarua": dynamic(() => import("./library/midia-off/PlacaRua").then((mod) => mod.PlacaRua)),
  "placasuspensa": dynamic(() => import("./library/eventos-ativacoes/PlacaSuspensa").then((mod) => mod.PlacaSuspensa)),
  "planner": dynamic(() => import("./library/educacional/Planner").then((mod) => mod.Planner)),
  "planoaula": dynamic(() => import("./library/educacional/PlanoAula").then((mod) => mod.PlanoAula)),
  "politicabeneficios": dynamic(() => import("./library/endomarketing/PoliticaBeneficios").then((mod) => mod.PoliticaBeneficios)),
  "politicacodigoetica": dynamic(() => import("./library/endomarketing/PoliticaCodigoEtica").then((mod) => mod.PoliticaCodigoEtica)),
  "politicadiversidade": dynamic(() => import("./library/endomarketing/PoliticaDiversidade").then((mod) => mod.PoliticaDiversidade)),
  "politicahomeoffice": dynamic(() => import("./library/endomarketing/PoliticaHomeOffice").then((mod) => mod.PoliticaHomeOffice)),
  "politicaprivacidade": dynamic(() => import("./library/endomarketing/PoliticaPrivacidade").then((mod) => mod.PoliticaPrivacidade)),
  "pontagondola": dynamic(() => import("./library/eventos-ativacoes/PontaGondola").then((mod) => mod.PontaGondola)),
  "portafolder": dynamic(() => import("./library/eventos-ativacoes/PortaFolder").then((mod) => mod.PortaFolder)),
  "portalinflavel": dynamic(() => import("./library/eventos-ativacoes/PortalInflavel").then((mod) => mod.PortalInflavel)),
  "postblog": dynamic(() => import("./library/conteudo-editorial/PostBlog").then((mod) => mod.PostBlog)),
  "postereducativo": dynamic(() => import("./library/educacional/PosterEducativo").then((mod) => mod.PosterEducativo)),
  "powerbank": dynamic(() => import("./library/eventos-ativacoes/PowerBank").then((mod) => mod.PowerBank)),
  "pressreleaseevento": dynamic(() => import("./library/conteudo-editorial/PressReleaseEvento").then((mod) => mod.PressReleaseEvento)),
  "pressreleaselancamento": dynamic(() => import("./library/conteudo-editorial/PressReleaseLancamento").then((mod) => mod.PressReleaseLancamento)),
  "pressreleasepadrao": dynamic(() => import("./library/conteudo-editorial/PressReleasePadrao").then((mod) => mod.PressReleasePadrao)),
  "pressreleaseparceria": dynamic(() => import("./library/conteudo-editorial/PressReleaseParceria").then((mod) => mod.PressReleaseParceria)),
  "pressreleasepremio": dynamic(() => import("./library/conteudo-editorial/PressReleasePremio").then((mod) => mod.PressReleasePremio)),
  "produtodetalhes": dynamic(() => import("./library/ecommerce/ProdutoDetalhes").then((mod) => mod.ProdutoDetalhes)),
  "quiosquerua": dynamic(() => import("./library/midia-off/QuiosqueRua").then((mod) => mod.QuiosqueRua)),
  "radioboletim": dynamic(() => import("./library/midia-off/RadioBoletim").then((mod) => mod.RadioBoletim)),
  "radiochamada": dynamic(() => import("./library/midia-off/RadioChamada").then((mod) => mod.RadioChamada)),
  "radioclassificado": dynamic(() => import("./library/midia-off/RadioClassificado").then((mod) => mod.RadioClassificado)),
  "radiocomunicado": dynamic(() => import("./library/midia-off/RadioComunicado").then((mod) => mod.RadioComunicado)),
  "radioconcurso": dynamic(() => import("./library/midia-off/RadioConcurso").then((mod) => mod.RadioConcurso)),
  "radioentrevista": dynamic(() => import("./library/midia-off/RadioEntrevista").then((mod) => mod.RadioEntrevista)),
  "radioevento": dynamic(() => import("./library/midia-off/RadioEvento").then((mod) => mod.RadioEvento)),
  "radioflash": dynamic(() => import("./library/midia-off/RadioFlash").then((mod) => mod.RadioFlash)),
  "radiohorario": dynamic(() => import("./library/midia-off/RadioHorario").then((mod) => mod.RadioHorario)),
  "radioinstitucional": dynamic(() => import("./library/midia-off/RadioInstitucional").then((mod) => mod.RadioInstitucional)),
  "radiojingle": dynamic(() => import("./library/midia-off/RadioJingle").then((mod) => mod.RadioJingle)),
  "radioofertas": dynamic(() => import("./library/midia-off/RadioOfertas").then((mod) => mod.RadioOfertas)),
  "radiopatrocinio": dynamic(() => import("./library/midia-off/RadioPatrocinio").then((mod) => mod.RadioPatrocinio)),
  "radiopodcast": dynamic(() => import("./library/midia-off/RadioPodcast").then((mod) => mod.RadioPodcast)),
  "radiopromocao": dynamic(() => import("./library/midia-off/RadioPromocao").then((mod) => mod.RadioPromocao)),
  "radiospot15s": dynamic(() => import("./library/midia-off/RadioSpot15s").then((mod) => mod.RadioSpot15s)),
  "radiospot30s": dynamic(() => import("./library/midia-off/RadioSpot30s").then((mod) => mod.RadioSpot30s)),
  "radiospot60s": dynamic(() => import("./library/midia-off/RadioSpot60s").then((mod) => mod.RadioSpot60s)),
  "radiotestemunhal": dynamic(() => import("./library/midia-off/RadioTestemunhal").then((mod) => mod.RadioTestemunhal)),
  "radiovinheta": dynamic(() => import("./library/midia-off/RadioVinheta").then((mod) => mod.RadioVinheta)),
  "receptiondesk": dynamic(() => import("./library/eventos-ativacoes/ReceptionDesk").then((mod) => mod.ReceptionDesk)),
  "recomendacoes": dynamic(() => import("./library/ecommerce/Recomendacoes").then((mod) => mod.Recomendacoes)),
  "redditpost": dynamic(() => import("./library/social/RedditPost").then((mod) => mod.RedditPost)),
  "relatoriocapa": dynamic(() => import("./library/apresentacoes/RelatorioCapa").then((mod) => mod.RelatorioCapa)),
  "relatoriocontracapa": dynamic(() => import("./library/apresentacoes/RelatorioContracapa").then((mod) => mod.RelatorioContracapa)),
  "relatorioequipe": dynamic(() => import("./library/apresentacoes/RelatorioEquipe").then((mod) => mod.RelatorioEquipe)),
  "relatoriofinanceiro": dynamic(() => import("./library/apresentacoes/RelatorioFinanceiro").then((mod) => mod.RelatorioFinanceiro)),
  "relatoriogovernanca": dynamic(() => import("./library/apresentacoes/RelatorioGovernanca").then((mod) => mod.RelatorioGovernanca)),
  "relatoriomensagem": dynamic(() => import("./library/apresentacoes/RelatorioMensagem").then((mod) => mod.RelatorioMensagem)),
  "relatorioperspectivas": dynamic(() => import("./library/apresentacoes/RelatorioPerspectivas").then((mod) => mod.RelatorioPerspectivas)),
  "relatorioresultados": dynamic(() => import("./library/apresentacoes/RelatorioResultados").then((mod) => mod.RelatorioResultados)),
  "relatoriosustentabilidade": dynamic(() => import("./library/apresentacoes/RelatorioSustentabilidade").then((mod) => mod.RelatorioSustentabilidade)),
  "relatoriovisao": dynamic(() => import("./library/apresentacoes/RelatorioVisao").then((mod) => mod.RelatorioVisao)),
  "relogiorua": dynamic(() => import("./library/midia-off/RelogioRua").then((mod) => mod.RelogioRua)),
  "review": dynamic(() => import("./library/conteudo-editorial/Review").then((mod) => mod.Review)),
  "revistaadesivo": dynamic(() => import("./library/midia-off/RevistaAdesivo").then((mod) => mod.RevistaAdesivo)),
  "revistabooklet": dynamic(() => import("./library/midia-off/RevistaBooklet").then((mod) => mod.RevistaBooklet)),
  "revistacapa": dynamic(() => import("./library/midia-off/RevistaCapa").then((mod) => mod.RevistaCapa)),
  "revistacoluna": dynamic(() => import("./library/midia-off/RevistaColuna").then((mod) => mod.RevistaColuna)),
  "revistacontracapa": dynamic(() => import("./library/midia-off/RevistaContraCapa").then((mod) => mod.RevistaContraCapa)),
  "revistaencarte": dynamic(() => import("./library/midia-off/RevistaEncarte").then((mod) => mod.RevistaEncarte)),
  "revistailhote": dynamic(() => import("./library/midia-off/RevistaIlhote").then((mod) => mod.RevistaIlhote)),
  "revistainterativa": dynamic(() => import("./library/midia-off/RevistaInterativa").then((mod) => mod.RevistaInterativa)),
  "revistameiapagina": dynamic(() => import("./library/midia-off/RevistaMeiaPagina").then((mod) => mod.RevistaMeiaPagina)),
  "revistaorelha": dynamic(() => import("./library/midia-off/RevistaOrelha").then((mod) => mod.RevistaOrelha)),
  "revistapaginadupla": dynamic(() => import("./library/midia-off/RevistaPaginaDupla").then((mod) => mod.RevistaPaginaDupla)),
  "revistapaginasimples": dynamic(() => import("./library/midia-off/RevistaPaginaSimples").then((mod) => mod.RevistaPaginaSimples)),
  "revistapopup": dynamic(() => import("./library/midia-off/RevistaPopup").then((mod) => mod.RevistaPopup)),
  "revistaquartacapa": dynamic(() => import("./library/midia-off/RevistaQuartaCapa").then((mod) => mod.RevistaQuartaCapa)),
  "revistaquartapagina": dynamic(() => import("./library/midia-off/RevistaQuartaPagina").then((mod) => mod.RevistaQuartaPagina)),
  "revistaquartopagina": dynamic(() => import("./library/midia-off/RevistaQuartoPagina").then((mod) => mod.RevistaQuartoPagina)),
  "revistarodape": dynamic(() => import("./library/midia-off/RevistaRodape").then((mod) => mod.RevistaRodape)),
  "revistasample": dynamic(() => import("./library/midia-off/RevistaSample").then((mod) => mod.RevistaSample)),
  "revistasegundacapa": dynamic(() => import("./library/midia-off/RevistaSegundaCapa").then((mod) => mod.RevistaSegundaCapa)),
  "revistaterceiracapa": dynamic(() => import("./library/midia-off/RevistaTerceiraCapa").then((mod) => mod.RevistaTerceiraCapa)),
  "sinalizacaobanheiro": dynamic(() => import("./library/eventos-ativacoes/SinalizacaoBanheiro").then((mod) => mod.SinalizacaoBanheiro)),
  "sinalizacaoemergencia": dynamic(() => import("./library/eventos-ativacoes/SinalizacaoEmergencia").then((mod) => mod.SinalizacaoEmergencia)),
  "slackmessage": dynamic(() => import("./library/social-batch2/SlackMessage").then((mod) => mod.SlackMessage)),
  "slackthread": dynamic(() => import("./library/social-batch2/SlackThread").then((mod) => mod.SlackThread)),
  "slideaulacapa": dynamic(() => import("./library/educacional/SlideAulaCapa").then((mod) => mod.SlideAulaCapa)),
  "slideconteudo": dynamic(() => import("./library/educacional/SlideConteudo").then((mod) => mod.SlideConteudo)),
  "slideexercicio": dynamic(() => import("./library/educacional/SlideExercicio").then((mod) => mod.SlideExercicio)),
  "slidequiz": dynamic(() => import("./library/educacional/SlideQuiz").then((mod) => mod.SlideQuiz)),
  "slideresumo": dynamic(() => import("./library/educacional/SlideResumo").then((mod) => mod.SlideResumo)),
  "snapchatsnap": dynamic(() => import("./library/social/SnapchatSnap").then((mod) => mod.SnapchatSnap)),
  "snapchatstory": dynamic(() => import("./library/social/SnapchatStory").then((mod) => mod.SnapchatStory)),
  "spotifyartist": dynamic(() => import("./library/midia-on/SpotifyArtist").then((mod) => mod.SpotifyArtist)),
  "spotifyplaylist": dynamic(() => import("./library/social/SpotifyPlaylist").then((mod) => mod.SpotifyPlaylist)),
  "spotifypodcast": dynamic(() => import("./library/social/SpotifyPodcast").then((mod) => mod.SpotifyPodcast)),
  "spotifywrapped": dynamic(() => import("./library/midia-on/SpotifyWrapped").then((mod) => mod.SpotifyWrapped)),
  "squeeze": dynamic(() => import("./library/eventos-ativacoes/Squeeze").then((mod) => mod.Squeeze)),
  "stoppergondola": dynamic(() => import("./library/eventos-ativacoes/StopperGondola").then((mod) => mod.StopperGondola)),
  "substacknewsletter": dynamic(() => import("./library/social-batch2/SubstackNewsletter").then((mod) => mod.SubstackNewsletter)),
  "substacksubscribe": dynamic(() => import("./library/social-batch2/SubstackSubscribe").then((mod) => mod.SubstackSubscribe)),
  "telaoprojecao": dynamic(() => import("./library/eventos-ativacoes/TelaoProjecao").then((mod) => mod.TelaoProjecao)),
  "telegramchannel": dynamic(() => import("./library/social/TelegramChannel").then((mod) => mod.TelegramChannel)),
  "telegrammessage": dynamic(() => import("./library/social/TelegramMessage").then((mod) => mod.TelegramMessage)),
  "template": dynamic(() => import("./library/educacional/Template").then((mod) => mod.Template)),
  "testador": dynamic(() => import("./library/eventos-ativacoes/Testador").then((mod) => mod.Testador)),
  "threadspost": dynamic(() => import("./library/midia-on/ThreadsPost").then((mod) => mod.ThreadsPost)),
  "tiktokcomment": dynamic(() => import("./library/social/TikTokComment").then((mod) => mod.TikTokComment)),
  "tiktokduet": dynamic(() => import("./library/midia-on/TikTokDuet").then((mod) => mod.TikTokDuet)),
  "tiktokeffect": dynamic(() => import("./library/midia-on/TikTokEffect").then((mod) => mod.TikTokEffect)),
  "tiktoklive": dynamic(() => import("./library/midia-on/TikTokLive").then((mod) => mod.TikTokLive)),
  "tiktokprofile": dynamic(() => import("./library/social/TikTokProfile").then((mod) => mod.TikTokProfile)),
  "tiktokstitch": dynamic(() => import("./library/midia-on/TikTokStitch").then((mod) => mod.TikTokStitch)),
  "tiktokvideo": dynamic(() => import("./library/social/TikTokVideo").then((mod) => mod.TikTokVideo)),
  "totemdirecional": dynamic(() => import("./library/eventos-ativacoes/TotemDirecional").then((mod) => mod.TotemDirecional)),
  "totemexterno": dynamic(() => import("./library/eventos-ativacoes/TotemExterno").then((mod) => mod.TotemExterno)),
  "totemrua": dynamic(() => import("./library/midia-off/TotemRua").then((mod) => mod.TotemRua)),
  "totensentrada": dynamic(() => import("./library/eventos-ativacoes/TotensEntrada").then((mod) => mod.TotensEntrada)),
  "tunelinflavel": dynamic(() => import("./library/eventos-ativacoes/TunelInflavel").then((mod) => mod.TunelInflavel)),
  "tutorial": dynamic(() => import("./library/conteudo-editorial/Tutorial").then((mod) => mod.Tutorial)),
  "tvanimacao": dynamic(() => import("./library/midia-off/TVAnimacao").then((mod) => mod.TVAnimacao)),
  "tvbumper": dynamic(() => import("./library/midia-off/TVBumper").then((mod) => mod.TVBumper)),
  "tvcinema": dynamic(() => import("./library/midia-off/TVCinema").then((mod) => mod.TVCinema)),
  "tvcommercial15s": dynamic(() => import("./library/midia-off/TVCommercial15s").then((mod) => mod.TVCommercial15s)),
  "tvcommercial30s": dynamic(() => import("./library/midia-off/TVCommercial30s").then((mod) => mod.TVCommercial30s)),
  "tvcommercial60s": dynamic(() => import("./library/midia-off/TVCommercial60s").then((mod) => mod.TVCommercial60s)),
  "tvcomparativo": dynamic(() => import("./library/midia-off/TVComparativo").then((mod) => mod.TVComparativo)),
  "tvcorporativaaniversariantes": dynamic(() => import("./library/endomarketing/TVCorporativaAniversariantes").then((mod) => mod.TVCorporativaAniversariantes)),
  "tvcorporativaavisos": dynamic(() => import("./library/endomarketing/TVCorporativaAvisos").then((mod) => mod.TVCorporativaAvisos)),
  "tvcorporativaboasvindas": dynamic(() => import("./library/endomarketing/TVCorporativaBoasVindas").then((mod) => mod.TVCorporativaBoasVindas)),
  "tvcorporativacampanha": dynamic(() => import("./library/endomarketing/TVCorporativaCampanha").then((mod) => mod.TVCorporativaCampanha)),
  "tvcorporativacardapio": dynamic(() => import("./library/endomarketing/TVCorporativaCardapio").then((mod) => mod.TVCorporativaCardapio)),
  "tvcorporativaclima": dynamic(() => import("./library/endomarketing/TVCorporativaClima").then((mod) => mod.TVCorporativaClima)),
  "tvcorporativaeventos": dynamic(() => import("./library/endomarketing/TVCorporativaEventos").then((mod) => mod.TVCorporativaEventos)),
  "tvcorporativahorarios": dynamic(() => import("./library/endomarketing/TVCorporativaHorarios").then((mod) => mod.TVCorporativaHorarios)),
  "tvcorporativakpis": dynamic(() => import("./library/endomarketing/TVCorporativaKPIs").then((mod) => mod.TVCorporativaKPIs)),
  "tvcorporativametas": dynamic(() => import("./library/endomarketing/TVCorporativaMetas").then((mod) => mod.TVCorporativaMetas)),
  "tvcorporativareconhecimento": dynamic(() => import("./library/endomarketing/TVCorporativaReconhecimento").then((mod) => mod.TVCorporativaReconhecimento)),
  "tvcorporativaresultados": dynamic(() => import("./library/endomarketing/TVCorporativaResultados").then((mod) => mod.TVCorporativaResultados)),
  "tvcorporativaseguranca": dynamic(() => import("./library/endomarketing/TVCorporativaSeguranca").then((mod) => mod.TVCorporativaSeguranca)),
  "tvcorporativatreinamentos": dynamic(() => import("./library/endomarketing/TVCorporativaTreinamentos").then((mod) => mod.TVCorporativaTreinamentos)),
  "tvcorporativavagas": dynamic(() => import("./library/endomarketing/TVCorporativaVagas").then((mod) => mod.TVCorporativaVagas)),
  "tvdemonstracao": dynamic(() => import("./library/midia-off/TVDemonstracao").then((mod) => mod.TVDemonstracao)),
  "tvinforme": dynamic(() => import("./library/midia-off/TVInforme").then((mod) => mod.TVInforme)),
  "tvinstitucional": dynamic(() => import("./library/midia-off/TVInstitucional").then((mod) => mod.TVInstitucional)),
  "tvlancamento": dynamic(() => import("./library/midia-off/TVLancamento").then((mod) => mod.TVLancamento)),
  "tvlegenda": dynamic(() => import("./library/midia-off/TVLegenda").then((mod) => mod.TVLegenda)),
  "tvpatrocinio": dynamic(() => import("./library/midia-off/TVPatrocinio").then((mod) => mod.TVPatrocinio)),
  "tvproductplacement": dynamic(() => import("./library/midia-off/TVProductPlacement").then((mod) => mod.TVProductPlacement)),
  "tvpromocional": dynamic(() => import("./library/midia-off/TVPromocional").then((mod) => mod.TVPromocional)),
  "tvsazonal": dynamic(() => import("./library/midia-off/TVSazonal").then((mod) => mod.TVSazonal)),
  "tvsobreposto": dynamic(() => import("./library/midia-off/TVSobreposto").then((mod) => mod.TVSobreposto)),
  "tvteleshopping": dynamic(() => import("./library/midia-off/TVTeleshopping").then((mod) => mod.TVTeleshopping)),
  "tvtestemunhal": dynamic(() => import("./library/midia-off/TVTestemunhal").then((mod) => mod.TVTestemunhal)),
  "tvvinheta": dynamic(() => import("./library/midia-off/TVVinheta").then((mod) => mod.TVVinheta)),
  "twitchchat": dynamic(() => import("./library/social-batch2/TwitchChat").then((mod) => mod.TwitchChat)),
  "twitchclip": dynamic(() => import("./library/social-batch2/TwitchClip").then((mod) => mod.TwitchClip)),
  "twitchprofile": dynamic(() => import("./library/social-batch2/TwitchProfile").then((mod) => mod.TwitchProfile)),
  "twitchstream": dynamic(() => import("./library/social-batch2/TwitchStream").then((mod) => mod.TwitchStream)),
  "twitterad": dynamic(() => import("./library/social/TwitterAd").then((mod) => mod.TwitterAd)),
  "twitterlist": dynamic(() => import("./library/midia-on/TwitterList").then((mod) => mod.TwitterList)),
  "twittermoment": dynamic(() => import("./library/midia-on/TwitterMoment").then((mod) => mod.TwitterMoment)),
  "twitterpoll": dynamic(() => import("./library/midia-on/TwitterPoll").then((mod) => mod.TwitterPoll)),
  "twitterpost": dynamic(() => import("./library/social/TwitterPost").then((mod) => mod.TwitterPost)),
  "twitterprofile": dynamic(() => import("./library/social/TwitterProfile").then((mod) => mod.TwitterProfile)),
  "twitterspace": dynamic(() => import("./library/midia-on/TwitterSpace").then((mod) => mod.TwitterSpace)),
  "twitterthread": dynamic(() => import("./library/social/TwitterThread").then((mod) => mod.TwitterThread)),
  "uniforme": dynamic(() => import("./library/branding/Uniforme").then((mod) => mod.Uniforme)),
  "whatsappbroadcast": dynamic(() => import("./library/midia-on/WhatsAppBroadcast").then((mod) => mod.WhatsAppBroadcast)),
  "whatsappbusiness": dynamic(() => import("./library/social/WhatsAppBusiness").then((mod) => mod.WhatsAppBusiness)),
  "whatsappcall": dynamic(() => import("./library/midia-on/WhatsAppCall").then((mod) => mod.WhatsAppCall)),
  "whatsappgroup": dynamic(() => import("./library/midia-on/WhatsAppGroup").then((mod) => mod.WhatsAppGroup)),
  "whatsappmessage": dynamic(() => import("./library/social/WhatsAppMessage").then((mod) => mod.WhatsAppMessage)),
  "whatsapppoll": dynamic(() => import("./library/midia-on/WhatsAppPoll").then((mod) => mod.WhatsAppPoll)),
  "whatsappstatus": dynamic(() => import("./library/social/WhatsAppStatus").then((mod) => mod.WhatsAppStatus)),
  "wishlist": dynamic(() => import("./library/ecommerce/Wishlist").then((mod) => mod.Wishlist)),
  "wobblemobile": dynamic(() => import("./library/eventos-ativacoes/WobbleMobile").then((mod) => mod.WobbleMobile)),
  "workbook": dynamic(() => import("./library/educacional/Workbook").then((mod) => mod.Workbook)),
  "youtubebanner": dynamic(() => import("./library/social/YouTubeBanner").then((mod) => mod.YouTubeBanner)),
  "youtubecommunity": dynamic(() => import("./library/social/YouTubeCommunity").then((mod) => mod.YouTubeCommunity)),
  "youtubelive": dynamic(() => import("./library/midia-on/YouTubeLive").then((mod) => mod.YouTubeLive)),
  "youtubemembership": dynamic(() => import("./library/midia-on/YouTubeMembership").then((mod) => mod.YouTubeMembership)),
  "youtubeplaylist": dynamic(() => import("./library/midia-on/YouTubePlaylist").then((mod) => mod.YouTubePlaylist)),
  "youtubepremiere": dynamic(() => import("./library/midia-on/YouTubePremiere").then((mod) => mod.YouTubePremiere)),
  "youtubeshorts": dynamic(() => import("./library/social/YouTubeShorts").then((mod) => mod.YouTubeShorts)),
  "youtubesuperchat": dynamic(() => import("./library/midia-on/YouTubeSuperchat").then((mod) => mod.YouTubeSuperchat)),
  "youtubethumbnail": dynamic(() => import("./library/social/YouTubeThumbnail").then((mod) => mod.YouTubeThumbnail)),
  "youtubevideo": dynamic(() => import("./library/social/YouTubeVideo").then((mod) => mod.YouTubeVideo)),
};

export const mockupRegistry = registry;

export const normalizeMockupKey = (value: string) =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");

export const buildMockupKeyCandidates = (params: { platform?: string; format?: string; platformLabel?: string; }): string[] => {
  const platform = params.platform || "";
  const format = params.format || "";
  const label = params.platformLabel || platform;
  const formatStripped = format
    .replace(/\b\d+\s*[xX:]\s*\d+\b/g, '')
    .replace(/\b\d+(px|s|sec)?\b/gi, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
  const formatAliases = [
    formatStripped,
    formatStripped.replace(/feed/gi, 'post'),
    formatStripped.replace(/post/gi, 'post'),
    formatStripped.replace(/carrossel/gi, 'carousel'),
    formatStripped.replace(/carousel/gi, 'carousel'),
    formatStripped.replace(/stories/gi, 'story'),
    formatStripped.replace(/reels/gi, 'reel'),
    formatStripped.replace(/capa/gi, 'cover'),
    formatStripped.replace(/perfil/gi, 'profile'),
  ];
  const platformAliases = [platform, label];
  const platformKey = normalizeMockupKey(platform);
  if (platformKey === 'x') platformAliases.push('twitter');
  if (platformKey === 'twitter') platformAliases.push('x');
  const raw = [
    ...platformAliases.map((item) => `${item}${format}`),
    ...platformAliases.map((item) => `${item} ${format}`),
    ...platformAliases.flatMap((item) => formatAliases.map((fmt) => `${item}${fmt}`)),
    ...platformAliases.flatMap((item) => formatAliases.map((fmt) => `${item} ${fmt}`)),
    format,
    ...formatAliases,
  ];
  const keys = raw.map((item) => normalizeMockupKey(item)).filter(Boolean);
  return Array.from(new Set(keys));
};

export const resolveMockupComponent = (keys: string[]): MockupComponent | null => {
  for (const key of keys) {
    if (registry[key]) return registry[key];
  }
  return null;
};

const STOPWORDS = new Set([
  'de',
  'da',
  'do',
  'das',
  'dos',
  'e',
  'em',
  'para',
  'com',
  'sem',
  'no',
  'na',
  'nos',
  'nas',
  'a',
  'o',
  'os',
  'as',
]);

const tokenize = (value: string) =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .split(' ')
    .map((token) => token.trim())
    .filter((token) => token.length > 1 && !STOPWORDS.has(token));

export const findBestMockupKey = (params: {
  productionType?: string;
  platform?: string;
  format?: string;
}): string | null => {
  const platformTokens = tokenize(params.platform || "");
  const formatTokens = tokenize(params.format || "");
  const productionTokens = tokenize(params.productionType || "");
  const tokens = Array.from(new Set([...platformTokens, ...formatTokens, ...productionTokens]));
  if (!tokens.length) return null;

  let bestKey: string | null = null;
  let bestScore = 0;

  for (const key of Object.keys(registry)) {
    let score = 0;
    for (const token of tokens) {
      const normalizedToken = normalizeMockupKey(token);
      if (!normalizedToken) continue;
      if (key.includes(normalizedToken)) {
        score += normalizedToken.length * 2;
      }
    }
    if (platformTokens.some((token) => key.includes(normalizeMockupKey(token)))) {
      score += 5;
    }
    if (formatTokens.some((token) => key.includes(normalizeMockupKey(token)))) {
      score += 3;
    }
    if (score > bestScore) {
      bestScore = score;
      bestKey = key;
    }
  }

  if (bestScore < 4) return null;
  return bestKey;
};
