[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'npm install -g pnpm@9',
  'if [ "$RAILWAY_SERVICE_NAME" = "edro-web" ]; then pnpm install --filter "@edro/web..." --no-frozen-lockfile; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-freelancer" ]; then pnpm install --filter "@edro/web-freelancer..." --no-frozen-lockfile; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-cliente" ]; then pnpm install --filter "@edro/web-cliente..." --no-frozen-lockfile; else pnpm install --filter "@edro/backend..." --no-frozen-lockfile; fi'
]

[phases.build]
cmds = [
  'if [ "$RAILWAY_SERVICE_NAME" = "edro-web" ]; then pnpm --filter @edro/web run build; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-freelancer" ]; then pnpm --filter @edro/web-freelancer run build; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-cliente" ]; then pnpm --filter @edro/web-cliente run build; else pnpm --filter @edro/backend run build; fi'
]


[start]
cmd = 'if [ "$RAILWAY_SERVICE_NAME" = "edro-web" ]; then pnpm --filter @edro/web run start; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-freelancer" ]; then pnpm --filter @edro/web-freelancer run start; elif [ "$RAILWAY_SERVICE_NAME" = "edro-web-cliente" ]; then pnpm --filter @edro/web-cliente run start; else pnpm --filter @edro/backend run start; fi'
