'use client';

import { useEffect, useRef, useState } from 'react';
import { apiGet, apiPostFormData } from '@/lib/api';

const FALLBACK_PROMPT = `Use the provided portrait photo as the identity reference and follow this exact fixed transformation ritual for the Edro freelancer avatar system.

Photo 1 is the real identity source of truth and must define who the person is.
Photo 2 is only a caricature bridge reference to move the result away from photorealism.
Photo 3 is the approved final style-family reference and must lock the final collection aesthetic.

MANDATORY VISUAL RITUAL:
Step 1: analyze the person’s real facial identity from photo 1.
Step 2: convert the person into a premium iconographic portrait.
Step 3: convert that iconographic portrait into a premium 3D toy character.
Step 4: apply the exact same solid flat brand-orange background.
Step 5: keep the final result centered, clean, and part of the same visual collection.

IDENTITY RULES:
- Preserve the person’s recognizable identity.
- Preserve face shape, face width, jawline, nose, eyes, eyebrows, mouth, hairline, hairstyle, beard or facial hair, skin tone, age impression, and gender presentation.
- Do not beautify the person.
- Do not make the face generic.
- Do not invent new features.
- Do not change the hairstyle arbitrarily.
- Keep the clothing simple and based on the original photo.

ICONOGRAPHIC STAGE RULES:
- Premium vector-style iconographic portrait.
- Clean contours.
- Smooth controlled shading.
- Simplified but faithful facial features.
- Centralized subject.
- Frontal or near-frontal composition.
- Minimal, polished, modern brand-avatar aesthetic.
- No scene elements.
- No environmental details.
- No text or logos.
- No painterly texture.
- No exaggerated caricature distortion.

3D TOY STAGE RULES:
- Transform the iconographic portrait into a premium designer-toy character.
- Large head, small body.
- Rounded proportions.
- Clean frontal neutral pose.
- Matte vinyl or soft-touch collectible material.
- Soft studio lighting.
- Minimal and polished finish.
- Stylized but still recognizable.
- No props.
- No dramatic action pose.
- No exaggerated facial expression.

BACKGROUND RULES:
- Always use the exact same solid flat background color.
- Exact brand orange: #F75A1B.
- No gradient.
- No texture.
- No vignette.
- No environmental background.

CONSISTENCY RULES:
- Every generated character must look like part of the same collection.
- Apply the same simplification logic to every face.
- Apply the same lighting logic to every toy.
- Apply the same composition logic to every portrait.
- Keep the same exact flat orange background in hex #F75A1B.
- Keep the same premium, clean, modern visual family across all outputs.`;

type AvatarResponse = {
  ok: boolean;
  avatar_url: string;
  avatar_provider?: string;
};

type AvatarConfigResponse = {
  ok: boolean;
  avatar_prompt: string;
  avatar_prompt_version?: string;
};

type Props = {
  file: File;
  onAccept: (avatarUrl: string) => void;
  onClose: () => void;
};

export default function AvatarGeneratorModal({ file, onAccept, onClose }: Props) {
  const [defaultPrompt, setDefaultPrompt] = useState(FALLBACK_PROMPT);
  const [prompt, setPrompt] = useState(FALLBACK_PROMPT);
  const [bootstrapping, setBootstrapping] = useState(true);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<string | null>(null);
  const [attempts, setAttempts] = useState(0);
  const [error, setError] = useState('');
  const sourceUrl = useRef(URL.createObjectURL(file)).current;
  const hasAutogenerated = useRef(false);

  useEffect(() => {
    let cancelled = false;

    apiGet<AvatarConfigResponse>('/freelancers/portal/me/avatar/config')
      .then((config) => {
        if (cancelled) return;
        const nextPrompt = config?.avatar_prompt?.trim() || FALLBACK_PROMPT;
        setDefaultPrompt(nextPrompt);
        setPrompt(nextPrompt);
      })
      .catch(() => {
        if (cancelled) return;
        setDefaultPrompt(FALLBACK_PROMPT);
        setPrompt(FALLBACK_PROMPT);
      })
      .finally(() => {
        if (!cancelled) setBootstrapping(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  // Auto-generate on first open
  useEffect(() => {
    if (bootstrapping || hasAutogenerated.current) return;
    hasAutogenerated.current = true;
    generate();
  }, [bootstrapping]);

  useEffect(() => {
    if (!loading) return;

    const startedAt = Date.now();
    setProgress(4);

    const interval = window.setInterval(() => {
      const elapsed = Date.now() - startedAt;
      const target = elapsed < 2_000
        ? 4 + (elapsed / 2_000) * 28
        : elapsed < 7_000
          ? 32 + ((elapsed - 2_000) / 5_000) * 38
          : elapsed < 16_000
            ? 70 + ((elapsed - 7_000) / 9_000) * 20
            : 90 + Math.min((elapsed - 16_000) / 12_000, 1) * 7;

      setProgress((current) => Math.max(current, Math.min(97, Math.round(target))));
    }, 250);

    return () => window.clearInterval(interval);
  }, [loading]);

  async function generate() {
    setLoading(true);
    setProgress(0);
    setError('');
    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('prompt', prompt);
      const res = await apiPostFormData<AvatarResponse>('/freelancers/portal/me/avatar', formData);
      setProgress(100);
      setResult(res.avatar_url);
      setAttempts((n) => n + 1);
    } catch (e: any) {
      setProgress(0);
      setError(e?.message ?? 'Erro ao gerar avatar');
    } finally {
      setLoading(false);
    }
  }

  function handleAccept() {
    if (result) onAccept(result);
  }

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 1000,
        background: 'rgba(0,0,0,0.82)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 16,
      }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        style={{
          background: '#1a1a2e',
          border: '1px solid rgba(255,255,255,0.10)',
          borderRadius: 20,
          width: '100%',
          maxWidth: 820,
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '18px 24px', borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
          <div>
            <div style={{ fontWeight: 700, fontSize: 16, color: '#fff' }}>Gerador de Avatar IA</div>
            <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.45)', marginTop: 2 }}>Ajuste o prompt e gere até chegar no resultado ideal</div>
          </div>
          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'rgba(255,255,255,0.5)', fontSize: 22, lineHeight: 1, padding: 4 }}
          >
            ×
          </button>
        </div>

        {/* Body */}
        <div style={{ flex: 1, overflowY: 'auto', padding: 24, display: 'flex', flexDirection: 'column', gap: 20 }}>

          {/* Previews */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
            {/* Source */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Foto original</span>
              <div style={{ aspectRatio: '1', borderRadius: 14, overflow: 'hidden', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' }}>
                <img src={sourceUrl} alt="Original" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>
            </div>

            {/* Result */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
                Resultado gerado {attempts > 1 ? `(tentativa ${attempts})` : ''}
              </span>
              <div style={{ aspectRatio: '1', borderRadius: 14, overflow: 'hidden', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
                {loading && (
                  <div style={{ width: '100%', maxWidth: 260, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14, padding: 24 }}>
                    <div style={{ width: 36, height: 36, borderRadius: '50%', border: '3px solid rgba(255,255,255,0.1)', borderTopColor: '#FF6600', animation: 'spin 0.9s linear infinite' }} />
                    <span style={{ fontSize: 12, color: 'rgba(255,255,255,0.4)' }}>Gerando com IA...</span>
                    <div style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 10 }}>
                      <div style={{ flex: 1, height: 8, borderRadius: 999, overflow: 'hidden', background: 'rgba(255,255,255,0.08)' }}>
                        <div
                          style={{
                            width: `${progress}%`,
                            height: '100%',
                            borderRadius: 999,
                            background: 'linear-gradient(90deg, #FF6600 0%, #FF8A33 100%)',
                            transition: 'width 240ms ease',
                          }}
                        />
                      </div>
                      <span style={{ minWidth: 36, fontSize: 12, fontWeight: 700, color: '#FF8A33', textAlign: 'right' }}>{progress}%</span>
                    </div>
                    <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.32)', textAlign: 'center' }}>
                      {progress < 35
                        ? 'Enviando referência'
                        : progress < 70
                          ? 'Gerando identidade'
                          : progress < 95
                            ? 'Refinando avatar'
                            : 'Finalizando'}
                    </span>
                  </div>
                )}
                {!loading && result && (
                  <img src={result} alt="Gerado" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                )}
                {!loading && !result && !error && (
                  <span style={{ fontSize: 12, color: 'rgba(255,255,255,0.25)' }}>Aguardando geração</span>
                )}
                {!loading && error && (
                  <span style={{ fontSize: 12, color: '#FA896B', textAlign: 'center', padding: 16 }}>{error}</span>
                )}
              </div>
            </div>
          </div>

          {/* Prompt editor */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <span style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Prompt</span>
              <button
                onClick={() => setPrompt(defaultPrompt)}
                style={{ fontSize: 11, color: 'rgba(255,255,255,0.35)', background: 'none', border: 'none', cursor: 'pointer', padding: '2px 6px' }}
              >
                Restaurar padrão
              </button>
            </div>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={8}
              disabled={loading || bootstrapping}
              style={{
                width: '100%',
                background: 'rgba(255,255,255,0.04)',
                border: '1px solid rgba(255,255,255,0.10)',
                borderRadius: 10,
                color: 'rgba(255,255,255,0.8)',
                fontSize: 13,
                lineHeight: 1.6,
                padding: '12px 14px',
                resize: 'vertical',
                fontFamily: 'inherit',
                outline: 'none',
                boxSizing: 'border-box',
              }}
            />
          </div>
        </div>

        {/* Footer */}
        <div style={{ padding: '16px 24px', borderTop: '1px solid rgba(255,255,255,0.08)', display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
          <button
            onClick={onClose}
            style={{ padding: '10px 20px', borderRadius: 10, border: '1px solid rgba(255,255,255,0.12)', background: 'transparent', color: 'rgba(255,255,255,0.5)', fontSize: 14, cursor: 'pointer' }}
          >
            Cancelar
          </button>

          {result && !loading && (
            <button
              onClick={generate}
              style={{ padding: '10px 20px', borderRadius: 10, border: '1px solid rgba(255,255,255,0.12)', background: 'rgba(255,255,255,0.06)', color: 'rgba(255,255,255,0.7)', fontSize: 14, cursor: 'pointer' }}
            >
              Tentar novamente
            </button>
          )}

          {!result && !loading && (
            <button
              onClick={generate}
              disabled={bootstrapping}
              style={{ padding: '10px 24px', borderRadius: 10, border: 'none', background: '#FF6600', color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer' }}
            >
              {bootstrapping ? 'Carregando prompt...' : 'Gerar'}
            </button>
          )}

          {loading && (
            <button
              disabled
              style={{ padding: '10px 24px', borderRadius: 10, border: 'none', background: 'rgba(255,102,0,0.4)', color: 'rgba(255,255,255,0.5)', fontSize: 14, fontWeight: 600, cursor: 'not-allowed' }}
            >
              Gerando…
            </button>
          )}

          {result && !loading && (
            <button
              onClick={handleAccept}
              style={{ padding: '10px 24px', borderRadius: 10, border: 'none', background: '#FF6600', color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer' }}
            >
              Aceitar ✓
            </button>
          )}
        </div>
      </div>

      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}
