'use client';

export const OPS_COPY = {
  shell: {
    badge: 'Beta',
    commandPlaceholder: 'Peça ao Jarvis ou digite um comando. Ex: reorganize minha semana',
    modules: 'Voltar aos módulos',
    newDemand: 'Nova demanda',
  },
  common: {
    contextEyebrow: 'Contexto da demanda',
    focusTitle: 'Detalhe da demanda',
    clientSubtitle: 'Contexto da conta',
    noOwner: 'Sem responsável',
    refreshDetail: 'Atualizar demanda',
    openDetail: 'Abrir demanda',
  },
  overview: {
    summaryExceptions: 'exceções',
    summaryUnassigned: 'sem responsável',
    summaryToday: 'batem hoje',
    summaryCheckpoints: 'checkpoints',
    pulseEyebrow: 'O que entrou',
    pulseTitle: 'Demandas para organizar',
    pulseSubtitle: 'Itens que ainda precisam de responsável, prazo ou decisão.',
    flowEyebrow: 'Andamento da agência',
    flowTitle: 'Fluxo das demandas',
    flowSubtitle: 'Veja em que etapa cada demanda está e onde a operação está travando.',
    flowRefresh: 'Atualizar painel',
    supportTitle: 'Demanda em foco',
    supportSubtitle: 'Veja o contexto da demanda selecionada e decida o próximo passo sem sair da Central.',
    emptyUnassigned: 'Nenhuma demanda está sem responsável agora.',
    emptyToday: 'Nenhuma entrega importante vence hoje.',
    emptyApprovals: 'Nenhuma aprovação do cliente está pressionando o fluxo agora.',
    emptyCheckpoints: 'Nenhum checkpoint operacional ficou pendente nesta leitura.',
    emptyStage: 'Nenhuma demanda pede atenção nesta etapa.',
    emptyExceptions: 'Nenhum problema urgente apareceu nesta leitura.',
    emptyCapacity: 'A equipe ainda não tem carga suficiente para mostrar aqui.',
    emptyAttentionClients: 'Nenhum cliente concentrou pressão nesta leitura.',
  },
  jobs: {
    summaryVisible: 'demandas visíveis',
    summaryUnassigned: 'sem responsável',
    summaryUrgent: 'urgentes',
    summaryStages: 'etapas ativas',
    triageEyebrow: 'Organização',
    triageTitle: 'Leitura da fila',
    triageSubtitle: 'Busque, filtre e escolha a demanda certa sem sair do fluxo.',
    flowEyebrow: 'Etapas',
    flowTitle: 'Demandas por etapa',
    flowSubtitle: 'Acompanhe as demandas por etapa, prioridade e responsável.',
    legacyKanban: 'Kanban antigo sairá daqui em breve',
    refresh: 'Atualizar fila',
    emptyList: 'Nenhuma demanda entrou nessa leitura.',
    emptyFocus: 'Escolha uma demanda para ver o contexto completo.',
    focusSubtitle: 'O detalhe fica fixo à direita para você decidir sem trocar de tela.',
    focusEmptySubtitle: 'Clique em qualquer linha para abrir o contexto da demanda.',
  },
  planner: {
    summaryPeople: 'pessoas no mapa',
    summaryOverload: 'sob pressão',
    summaryUnassigned: 'demandas sem responsável',
    title: 'Mapa da equipe',
    subtitle: 'Veja quem está livre, pressionado ou ainda comporta demanda nesta semana.',
    refresh: 'Atualizar alocação',
    emptyRow: 'Nenhuma demanda foi colocada com esta pessoa nesta leitura.',
    emptyUnassigned: 'Nenhuma demanda está sem responsável agora.',
    focusSubtitle: 'Veja o detalhe da demanda sem sair do mapa da semana.',
    focusEmptySubtitle: 'Clique em qualquer linha para abrir o contexto da demanda.',
    rulesTitle: 'Como esta leitura funciona',
  },
  agenda: {
    summaryDays: 'dias com impacto',
    summaryItems: 'demandas na agenda',
    summaryLayers: 'camadas ativas',
    summaryDistributed: 'pessoas na distribuição',
    layersEyebrow: 'O que entra na agenda',
    layersTitle: 'Leitura da semana',
    layersSubtitle: 'Mostre só o que realmente mexe na semana da agência. O calendário editorial continua separado.',
    viewCalendar: 'Calendário',
    viewDistribution: 'Distribuição da equipe',
    calendarEyebrow: 'Dias que pedem atenção',
    calendarTitle: 'Agenda da semana',
    calendarSubtitle: 'Entregas, aprovações, produção, reuniões e riscos que já mexem na semana.',
    distributionEyebrow: 'Distribuição dos jobs',
    distributionTitle: 'Semana por responsável',
    distributionSubtitle: 'Veja os jobs distribuídos entre a equipe ao longo dos dias úteis.',
    distributionHeaderTitle: 'Leitura da distribuição',
    distributionHeaderSubtitle: 'Cada linha mostra quem está com a demanda, em que dia ela está prevista e onde ainda existe folga.',
    unassignedTitle: 'Demandas sem responsável',
    unassignedSubtitle: 'Itens que ainda precisam de dono antes de entrarem na semana da equipe.',
    unassignedEmpty: 'Nenhuma demanda ficou solta nesta leitura.',
    refresh: 'Atualizar agenda',
    emptyLayer: 'Nenhuma demanda está mexendo nesta camada agora.',
    editorialLinkValue: 'Abrir calendário editorial',
    editorialLinkSubtitle: 'O calendário editorial segue separado da agenda da operação.',
    meetingsLinkValue: 'Abrir reuniões',
    meetingsLinkSubtitle: 'As reuniões continuam separadas, mas o impacto aparece aqui.',
    dayImpactSuffix: 'demanda(s) mexendo neste dia',
    emptyAgendaTitle: 'Nenhum dia em destaque',
    emptyAgendaDescription: 'Nenhuma demanda com prazo entrou na agenda para este filtro.',
    focusSubtitle: 'Veja o impacto da demanda na semana e aja sem sair da agenda.',
    focusEmptySubtitle: 'Clique em um item da agenda para abrir o contexto da demanda.',
    nextDaysTitle: 'Próximos dias',
    distributionEmptyTitle: 'Nenhuma distribuição disponível',
    distributionEmptyDescription: 'Ainda não há jobs alocados na semana para esta leitura.',
  },
  radar: {
    summaryCritical: 'riscos críticos',
    summaryHigh: 'riscos altos',
    summaryClients: 'clientes em zona vermelha',
    title: 'Riscos da operação',
    subtitle: 'Aqui ficam só as demandas que pedem decisão ou replanejamento antes de estourar no cliente.',
    refresh: 'Atualizar riscos',
    criticalSubtitle: 'Demandas que já exigem ação imediata.',
    highSubtitle: 'Demandas que ainda cabem na rotina, mas já precisam de atenção.',
    emptyCriticalTitle: 'Sem risco crítico',
    emptyCriticalDescription: 'Nenhuma demanda entrou na faixa mais grave agora.',
    emptyHigh: 'Nenhuma demanda ficou na faixa de risco alto agora.',
    focusSubtitle: 'Veja o contexto da demanda e aja antes do problema chegar no cliente.',
    focusEmptySubtitle: 'Clique em uma demanda para abrir o contexto do risco.',
    attentionClientsTitle: 'Clientes em atenção',
    attentionClientsEmpty: 'Nenhum cliente concentrou risco nesta leitura.',
    rulesTitle: 'Como o risco é lido',
  },
} as const;
