import 'dotenv/config';
import { z } from 'zod';

const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  JWT_SECRET: z.string().min(10),
  PORT: z.coerce.number().optional(),
  NODE_ENV: z
    .enum(['development', 'test', 'production', 'staging'])
    .default('development'),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_BASE_URL: z.string().url().default('https://api.openai.com/v1'),
  OPENAI_MODEL: z.string().default('gpt-4o-mini'),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().optional(),
  GEMINI_BASE_URL: z.string().optional(),
  GEMINI_ENDPOINT: z.string().optional(),
  GEMINI_RESPONSE_MIME: z.string().optional(),
  CLAUDE_API_KEY: z.string().optional(),
  ANTHROPIC_API_KEY: z.string().optional(),
  ANTHROPIC_MODEL: z.string().default('claude-sonnet-4-20250514'),
  ANTHROPIC_BASE_URL: z.string().url().default('https://api.anthropic.com'),
  CLAUDE_MODEL: z.string().optional(),
  CLAUDE_BASE_URL: z.string().optional(),
  CLAUDE_VERSION: z.string().optional(),
  ALLOWED_ORIGINS: z.string().optional(),
  EDRO_ALLOWED_DOMAINS: z.string().optional(),
  EDRO_ADMIN_EMAILS: z.string().optional(),
  EDRO_LOGIN_CODE_TTL_MINUTES: z.coerce.number().optional(),
  EDRO_LOGIN_ECHO_CODE: z.coerce.boolean().optional(),
  EDRO_LOGIN_SECRET: z.string().optional(),
  EDRO_ICLIPS_NOTIFY_EMAIL: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().optional(),
  FILE_STORAGE_ROOT: z.string().optional(),
  S3_BUCKET: z.string().optional(),
  S3_REGION: z.string().optional(),
  S3_ACCESS_KEY: z.string().optional(),
  S3_SECRET_KEY: z.string().optional(),
  S3_ENDPOINT: z.string().optional(),
  S3_FORCE_PATH_STYLE: z.coerce.boolean().optional(),
  JOBS_RUNNER_ENABLED: z.coerce.boolean().optional(),
  JOBS_RUNNER_INTERVAL_MS: z.coerce.number().optional(),
  MASTER_KEY_B64: z.string().optional(),
  OIDC_ISSUER_URL: z.string().optional(),
  OIDC_CLIENT_ID: z.string().optional(),
  OIDC_CLIENT_SECRET: z.string().optional(),
  OIDC_REDIRECT_URI: z.string().optional(),
  WEB_URL: z.string().optional(),
  PUBLIC_API_URL: z.string().optional(),
  PUBLISHER_GATEWAY_URL: z.string().optional(),
  GATEWAY_SHARED_SECRET: z.string().optional(),
  ENABLE_METRICS: z.coerce.boolean().optional(),
  CALENDAR_CSV_PATH: z.string().optional(),
  CALENDAR_YEAR: z.coerce.number().optional(),
  SOCIAL_DATA_API_URL: z.string().optional(),
  SOCIAL_DATA_API_KEY: z.string().optional(),
  META_GRAPH_VERSION: z.string().optional(),
  REPORTEI_BASE_URL: z.string().url().optional(),
  REPORTEI_TOKEN: z.string().optional(),
  CLIENT_INTEL_ENABLED: z.coerce.boolean().optional(),
  CLIENT_INTEL_INTERVAL_MS: z.coerce.number().optional(),
  CLIENT_INTEL_MAX_URLS: z.coerce.number().optional(),
  CLIENT_INTEL_MAX_DOCS: z.coerce.number().optional(),
  CLIENT_INTEL_MAX_CHARS: z.coerce.number().optional(),
  CALENDAR_RECALC_ENABLED: z.coerce.boolean().optional(),
  CALENDAR_RECALC_INTERVAL_MS: z.coerce.number().optional(),
  CALENDAR_RECALC_FROM: z.string().optional(),
  CALENDAR_RECALC_TO: z.string().optional(),
});

const parsed = envSchema.parse(process.env);

export const env = {
  ...parsed,
  CLAUDE_API_KEY: parsed.CLAUDE_API_KEY || parsed.ANTHROPIC_API_KEY,
};
