import { FastifyInstance } from 'fastify';
import healthRoutes from './health';
import authRoutes from './auth';
import ssoRoutes from './sso';
import edroRoutes from './edro';
import calendarRoutes from './calendar';
import connectorsRoutes from './connectors';
import postRulesRoutes from './posts.rules';
import postEditRoutes from './posts.edit';
import searchRoutes from './search';
import webhooksRoutes from './webhooks';
import flagsRoutes from './flags';
import libraryRoutes from './library';
import libraryJobsRoutes from './libraryJobs';
import postSourcesRoutes from './postSources';
import eventsRoutes from './events';
import clientsRoutes from './clients';
import clippingRoutes from './clipping';
import productionRoutes from './production';
import campaignsRoutes from './campaigns';
import securityRoutes from './security';
import recommendationRoutes from './recommendations';
import socialListeningRoutes from './socialListening';
import integrationRoutes from './integration';
import integrationHealthRoutes from './integrationHealthRoutes';
import mockupsRoutes from './mockups';
import planningRoutes from './planning';
import adminAiCostsRoutes from './adminAiCosts';
import adminUsersRoutes from './adminUsers';
import notificationsRoutes from './notifications';
import automationsRoutes from './automations';
import reportsRoutes from './reports';
import analyticsRoutes from './analytics';
import integrationDataRoutes from './integrationData';
import pautaInboxRoutes from './pautaInbox';
import tempPgVectorCheck from './_temp_pgvector_check';
import metaOAuthRoutes from './metaOAuth';
import darkFunnelRoutes from './darkFunnel';
import behaviorProfilesRoutes from './behaviorProfiles';
import learningRulesRoutes from './learningRules';
import adminReporteiRoutes from './adminReportei';
import freelancersRoutes from './freelancers';
import financialRoutes from './financial';
import portalClientRoutes from './portalClient';
import artworksRoutes from './artworks';
import studioCreativeRoutes from './studioCreative';
import studioCanvasRoutes from './studioCanvas';
import studioWorkflowRoutes from './studioWorkflow';
import studioRecipesRoutes from './studioRecipes';
import webhookWhatsAppRoutes from './webhookWhatsApp';
import meetingRoutes from './meetings';
import evolutionRoutes from './evolutionRoutes';
import webhookEvolutionRoutes from './webhookEvolution';
import whatsappInboxRoutes from './whatsappInbox';
import webhookInstagramRoutes from './webhookInstagram';
import webhookUniversalRoutes, { webhookAdminRoutes } from './webhookUniversal';
import { portalTokenRoutes } from './portalClient';
import gmailRoutes from './gmailRoutes';
import webhookGmailRoutes from './webhookGmail';
import googleCalendarRoutes from './googleCalendarRoutes';
import webhookGoogleCalendarRoutes from './webhookGoogleCalendar';
import webhookRecallRoutes from './webhookRecall';
import jobsRoutes from './jobs';
import operationsRoutes from './operations';
import peopleRoutes from './people';
import simulationRoutes from './simulation';
import competitorsRoutes from './competitors';

export async function registerRoutes(app: FastifyInstance) {
  app.register(tempPgVectorCheck);
  app.register(healthRoutes);

  app.register(authRoutes, { prefix: '/api' });
  app.register(ssoRoutes, { prefix: '/api' });
  app.register(metaOAuthRoutes, { prefix: '/api' });
  app.register(edroRoutes, { prefix: '/api' });
  app.register(calendarRoutes, { prefix: '/api' });
  app.register(connectorsRoutes, { prefix: '/api' });
  app.register(postRulesRoutes, { prefix: '/api' });
  app.register(postEditRoutes, { prefix: '/api' });
  app.register(searchRoutes, { prefix: '/api' });
  app.register(webhooksRoutes, { prefix: '/api' });
  app.register(flagsRoutes, { prefix: '/api' });
  app.register(libraryRoutes, { prefix: '/api' });
  app.register(libraryJobsRoutes, { prefix: '/api' });
  app.register(postSourcesRoutes, { prefix: '/api' });
  app.register(eventsRoutes, { prefix: '/api' });
  app.register(clientsRoutes, { prefix: '/api' });
  app.register(clippingRoutes, { prefix: '/api' });
  app.register(productionRoutes, { prefix: '/api' });
  app.register(campaignsRoutes, { prefix: '/api' });
  app.register(securityRoutes, { prefix: '/api' });
  app.register(recommendationRoutes, { prefix: '/api' });
  app.register(socialListeningRoutes, { prefix: '/api' });
  app.register(integrationRoutes, { prefix: '/api' });
  app.register(integrationHealthRoutes, { prefix: '/api' });
  app.register(mockupsRoutes, { prefix: '/api' });
  app.register(planningRoutes, { prefix: '/api' });
  app.register(adminAiCostsRoutes, { prefix: '/api' });
  app.register(adminUsersRoutes, { prefix: '/api' });
  app.register(notificationsRoutes, { prefix: '/api' });
  app.register(automationsRoutes, { prefix: '/api' });
  app.register(reportsRoutes, { prefix: '/api' });
  app.register(analyticsRoutes, { prefix: '/api' });
  app.register(integrationDataRoutes, { prefix: '/api' });
  app.register(pautaInboxRoutes, { prefix: '/api' });
  app.register(darkFunnelRoutes, { prefix: '/api' });
  app.register(behaviorProfilesRoutes, { prefix: '/api' });
  app.register(learningRulesRoutes, { prefix: '/api' });
  app.register(adminReporteiRoutes, { prefix: '/api' });
  app.register(freelancersRoutes, { prefix: '/api' });
  app.register(peopleRoutes, { prefix: '/api' });
  app.register(financialRoutes, { prefix: '/api' });
  app.register(portalClientRoutes, { prefix: '/api' });
  app.register(artworksRoutes, { prefix: '/api' });
  app.register(studioCreativeRoutes, { prefix: '/api' });
  app.register(studioCanvasRoutes, { prefix: '/api' });
  app.register(studioWorkflowRoutes, { prefix: '/api' });
  app.register(studioRecipesRoutes, { prefix: '/api' });
  // WhatsApp webhook — no /api prefix (Meta calls the raw path)
  app.register(webhookWhatsAppRoutes);
  // Evolution API webhook — no /api prefix
  app.register(webhookEvolutionRoutes);
  // Instagram DMs webhook — no /api prefix (Meta calls the raw path)
  app.register(webhookInstagramRoutes);
  // Universal inbound webhook — no /api prefix (Zapier/Make/n8n use raw URL)
  app.register(webhookUniversalRoutes);
  // Gmail Pub/Sub webhook — no /api prefix
  app.register(webhookGmailRoutes);
  // Google Calendar push notification — no /api prefix
  app.register(webhookGoogleCalendarRoutes);
  // Recall async webhooks — no /api prefix
  app.register(webhookRecallRoutes);
  app.register(meetingRoutes, { prefix: '/api' });
  app.register(evolutionRoutes, { prefix: '/api' });
  app.register(whatsappInboxRoutes, { prefix: '/api' });
  // Portal token routes (public + admin endpoints)
  app.register(portalTokenRoutes, { prefix: '/api' });
  app.register(gmailRoutes, { prefix: '/api' });
  app.register(googleCalendarRoutes, { prefix: '/api' });
  app.register(jobsRoutes, { prefix: '/api' });
  app.register(operationsRoutes, { prefix: '/api' });
  app.register(webhookAdminRoutes, { prefix: '/api' });
  app.register(simulationRoutes, { prefix: '/api' });
  app.register(competitorsRoutes, { prefix: '/api' });
}
